### ISSUE TITLE
Stuck on "Fetching Portal Info" on new portals

### ISSUE THREAD

**Issue by Talref** [SpikeHimself/XPortal#10]
Version 1.2.1, installed through Vortex, manually on home hosted server (same version, another machine running ubuntu).

Already present portals work as intended but as soon I add or destroy and recreate one I get a "fetching portal info" while hovering over them and can't do nothing, not even destroy them via building menu and they disappear from the working portal list.

**Comment by SpikeHimself** [comment]
Thanks for reporting!

Could you turn on debug logging and send me the BepInEx output logs of your server as well as your client?

**Comment by SpikeHimself** [comment]
Thanks for reporting @sirtodion! I have tested exhaustively on my end and am unable to reproduce this problem, so I'm still looking for BepInEx logs in order to get to the bottom of it.

**Comment by sirtodion** [comment]
> Thanks for reporting @sirtodion! I have tested exhaustively on my end and am unable to reproduce this problem, so I'm still looking for BepInEx logs in order to get to the bottom of it.

I am running another portal mod called TeleportEverything. Maybe thats not possible to do?

**Comment by SpikeHimself** [comment]
@sirtodion Maybe. Maybe not. Without output logs I do not have the information required to answer the question.

**Comment by Talref** [comment]
[LogOutput_client.log](https://github.com/SpikeHimself/XPortal/files/10662884/LogOutput_client.log)
[LogOutput_server.log](https://github.com/SpikeHimself/XPortal/files/10662887/LogOutput_server.log)

Client and server logs (with debug mode on)
![xportal](https://user-images.githubusercontent.com/44619895/216969921-1897be1b-3d41-4c7d-9065-937d1d9a0599.png)

How the problem presents itself in game (with or without debug mode the portal is locked and indestructible)

**Comment by Gotri1337** [comment]
+1 to all above , same at my server

**Comment by SpikeHimself** [comment]
> [LogOutput_client.log](https://github.com/SpikeHimself/XPortal/files/10662884/LogOutput_client.log) [LogOutput_server.log](https://github.com/SpikeHimself/XPortal/files/10662887/LogOutput_server.log)

Your server log contains no trace of any XPortal related messages. Did you upload the wrong logfile?

Judging by the contents of the client logfile, your game failed to detect that a new portal was placed. Do you get the error consistently, every single time you build a new portal? 

> EDIT: ValheimPlus is installed on both server and client but portal management (like the item hack) is disabled

Could you try disabling VH+ and see if that makes a difference?

**Comment by Talref** [comment]
What I did:
- Removed old logs
- Logged in Valheim with admin user
- Opened console and enabled debug mode
- traveled with a portal, destroyed a portal and rebuilt it, triggering the bug
- sent you the logs

Tried without V+ and works as intended. Try to replicate the bug with V+ installed on your side.

**Comment by SpikeHimself** [comment]
Apologies, I'm being stupid. I had "match case" enabled when I searched for "xportal" in your server log, so it didn't find it. D'oh!

Regardless, the issue is clear now - the mod is currently not compatible with VH+. I will look into how VH+ works and see if I can change XPortal's behaviour.

**Comment by Gotri1337** [comment]
ok i did - unistaled xportal , uploaded some other portal mod , all is gone , beehive i can kill other portal mod working. definitly somthing is wrong after the update of Xportal. anyway awsome work keep it going.

**Comment by SpikeHimself** [comment]
@Gotri1337 I think you commented on the wrong issue ;)

**Comment by Talref** [comment]
I can confirm that the bug is still present even when disabling V+ from its config file but still keeping it in the bepinex plugins folder. The only solution is to remove V+ from both client/server.

**Comment by SpikeHimself** [comment]
Thank you for testing that, @Talref. I will look into it.

**Comment by Gotri1337** [comment]
> @Gotri1337 I think you commented on the wrong issue ;)

naaa im in right place , had same problems with Xportal , and beehives :P that i cant kill:D , after this what i did all works as should .

**Comment by SpikeHimself** [comment]
@Gotri1337 This issue is not about beehives, that's issue #12. This issue is about portal placement not being detected.

@Talref @sirtodion @Gotri1337 Do you run any other mods besides VH+? If so, can you provide the full list?

**Comment by SpikeHimself** [comment]
[XPortal-v1.2.1-issue-10.zip](https://github.com/SpikeHimself/XPortal/files/10664198/XPortal-v1.2.1-issue-10.zip)

Could you test this test release and let me know the results?

**Comment by Gotri1337** [comment]
so the bug with xportal maybe had to do somthing with bhive , becouse when i did what i did all is gone , and all working , 
denikson-BepInExPack_Valheim-5.4.1901
ValheimPlus-ValheimPlus-9.9.11
ValheimModding-Jotunn-2.10.4
The_Bees_Decree-VALKEA-2.1.41
GoldenJude-Mineshafts-1.0.6
Smoothbrain-Resurrection-1.0.5
KukuPie-Kukus_Village-3.3.0
GemHunter1-FastTeleport-1.1.0
makail-ItemDrawers-0.5.0
OdinPlus-OdinHorse-1.1.0
OdinPlus-OdinCampsite-1.4.1
Smoothbrain-DarwinAwards-1.0.4
Tequila-Dvergr_Pieces-2.0.1
Balrond-balrond_dvergr_furniture-1.0.4
MSchmoecker-MultiUserChest-0.4.1
coemt-Belts-1.0.6
Yorimor-ToggleSprint-0.4.1
Vapok-AdventureBackpacks-1.5.9
Nextek-SpeedyPaths-1.0.6
OdinPlus-BoomStick-0.0.10
dannypacquiao-Valweed-0.3.4
OdinPlus-OdinArchitect-1.1.1
OdinPlus-OdinsSteelworks-0.1.10
MonsterLabZ-MonsterLabZ-2.9.3
Mokutan-MassFarming-1.5.0
OdinPlus-OdinsUndercroft-1.1.11
OdinPlus-OdinsHorsePen-1.0.4
OdinPlus-CraftyCartsRemake-3.0.8
OdinPlus-KnarrTheTrader-0.3.1
OhhLoz-HoneyPlus-5.1.2
sweetgiorni-AnyPortal-2.0.0

here is my list of what is on , i "think" all is working so far , im totaly new in this but i think lerning fast.

**Comment by Gotri1337** [comment]
still got few yellows lines in logs but dunno what to do with them xD

**Comment by SpikeHimself** [comment]
@Gotri1337 XPortal isn't in your list. I don't know if you left it out on purpose (because it's implied?), but you do also have AnyPortal in your list. XPortal is the _replacement_ for AnyPortal. They cannot work together.

**Comment by Talref** [comment]
> [XPortal-v1.2.1-issue-10.zip](https://github.com/SpikeHimself/XPortal/files/10664198/XPortal-v1.2.1-issue-10.zip)
> 
> Could you try using this test release and let me know the results? Only the client needs to change to this test, the server can continue using the original v1.2.1 release (for now).

It's fixed on my side. Nice Job!

**Comment by SpikeHimself** [comment]
That's good news, thank you very much for testing! I will include this fix in the next release (hopefully soon).

**Comment by Gotri1337** [comment]
> @Gotri1337 XPortal isn't in your list. I don't know if you left it out on purpose (because it's implied?), but you do also have AnyPortal in your list. XPortal is the _replacement_ for AnyPortal. They cannot work together.
> 
> Anyway, if you are having problems that are not related to the "fetching portal info" message, please create a new issue for those.

mate i instaled anyportal cos xportal gave me no portal options , after that i didnt had problems with portal and so on with hives , like im telling you im new im just trying to solve xportal issue with ya cos i like it better.

**Comment by SpikeHimself** [comment]
@Gotri1337 No worries, I just misunderstood your message then. These issues are fixed in the latest release so everything should be okay now! Thanks for your support.

**Comment by Gotri1337** [comment]
thanks for your work mate its just amazing what you ppl can do with this game - im just wonder why da hell " thay " dont do anything like it :P
