### ISSUE TITLE
Mod wont load on my server

### ISSUE THREAD

**Issue by meltdown1970** [SpikeHimself/XPortal#100]
I can get mod to load on client and works fine when running solo game on client computer, but when I connect to a server that i set up on a spare computer with this mod Jotunn says mod isnt loaded on server even though log file says it is.  It has an error about loading additional mod Xportal but I'm not sure why its saying that I only have the .dll in the plugins folder once. Thanks for the help.

from server log:
[Message:   BepInEx] BepInEx 5.4.23.0 - valheim_server (5/7/2024 7:15:30 PM)
[Info   :   BepInEx] Running under Unity v2022.3.17.5228416
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Jotunn 2.20.0]
[Info   :Jotunn.Main] Initializing ModCompatibility
[Info   :Jotunn.Main] Initializing SynchronizationManager
[Info   :Jotunn.Main] Initializing NetworkManager
[Info   :   BepInEx] Loading [XPortal 1.2.20]
[Info   :Jotunn.Main] Initializing GUIManager
[Info   :Jotunn.Main] Initializing MinimapManager
[Message:   BepInEx] Chainloader startup complete
[Info   :Jotunn.Managers.NetworkManager] Registering 2 custom RPCs

from client:
[Message:   BepInEx] BepInEx 5.4.22.0 - valheim (5/7/2024 12:10:59 PM)
[Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2202 from Thunderstore
[Info   :   BepInEx] Running under Unity v2022.3.17.5228416
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 9 plugins to load
[Info   :   BepInEx] Loading [Craft From Containers 3.5.1]
[Info   :   BepInEx] Loading [Tree Respawn 0.8.0]
[Info   :   BepInEx] Loading [Jotunn 2.20.0]
[Info   :Jotunn.Main] Initializing ModCompatibility
[Info   :Jotunn.Main] Initializing SynchronizationManager
[Info   :Jotunn.Main] Initializing NetworkManager
[Info   :   BepInEx] Loading [FarmGrid 0.5.0]
[Info   :   BepInEx] Loading [Quick Stack - Store - Sort - Trash - Restock 1.4.7]
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.2]
[Info   :   BepInEx] Loading [Build Camera 1.6.1]
[Info   :   BepInEx] Loading [StaminaSense 1.0.0]
[Info   :   BepInEx] Loading [XPortal 1.2.20]
[Info   :Jotunn.Main] Initializing GUIManager
[Info   :Jotunn.Main] Initializing InputManager
[Info   :Jotunn.Main] Initializing MinimapManager
[Info   :Jotunn.Main] Initializing PrefabManager
[Info   :Jotunn.Main] Initializing AssetManager
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Privilege Multiplayer is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] Privilege UserGeneratedContent is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] Privilege CrossPlay is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] 05/16/2024 14:12:53: Set background loading budget to Low
[Info   : Unity Log] TreeRespawn Loaded 6 seeds from D:\SteamLibrary\steamapps\common\Valheim\BepInEx\plugins\TreeRespawn\tree_dict.json
[Info   :Jotunn.Main] Initializing LocalizationManager
[Warning: Unity Log] 05/16/2024 14:12:53: Fetching PlatformPrefs 'GuiScale' before loading defaults
[Warning: Unity Log] 05/16/2024 14:12:53: Fetching PlatformPrefs 'GuiScale' before loading defaults
[Info   : Unity Log] 05/16/2024 14:12:54: Starting to load scene:start.unity (169d7618616154c03be07e9ad3af5893)
[Info   : Unity Log] 05/16/2024 14:12:54: Set background loading budget to Normal
[Info   : Unity Log] 05/16/2024 14:12:57: Set background loading budget to High

after attempting to log in here are the server and client logs

Server:
[Message:   BepInEx] BepInEx 5.4.23.0 - valheim_server (5/7/2024 7:15:30 PM)
[Info   :   BepInEx] Running under Unity v2022.3.17.5228416
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Jotunn 2.20.0]
[Info   :Jotunn.Main] Initializing ModCompatibility
[Info   :Jotunn.Main] Initializing SynchronizationManager
[Info   :Jotunn.Main] Initializing NetworkManager
[Info   :   BepInEx] Loading [XPortal 1.2.20]
[Info   :Jotunn.Main] Initializing GUIManager
[Info   :Jotunn.Main] Initializing MinimapManager
[Message:   BepInEx] Chainloader startup complete
[Info   :Jotunn.Managers.NetworkManager] Registering 2 custom RPCs
[Warning:Jotunn.Utils.ModCompatibility] Client loaded additional mod: XPortal
[Warning:Jotunn.Utils.ModCompatibility] RPC_Jotunn_ReceiveVersionData: Disconnecting modded client with incompatible version message. Mods are not compatible

client:
[Message:   BepInEx] BepInEx 5.4.22.0 - valheim (5/7/2024 12:10:59 PM)
[Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2202 from Thunderstore
[Info   :   BepInEx] Running under Unity v2022.3.17.5228416
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 9 plugins to load
[Info   :   BepInEx] Loading [Craft From Containers 3.5.1]
[Info   :   BepInEx] Loading [Tree Respawn 0.8.0]
[Info   :   BepInEx] Loading [Jotunn 2.20.0]
[Info   :Jotunn.Main] Initializing ModCompatibility
[Info   :Jotunn.Main] Initializing SynchronizationManager
[Info   :Jotunn.Main] Initializing NetworkManager
[Info   :   BepInEx] Loading [FarmGrid 0.5.0]
[Info   :   BepInEx] Loading [Quick Stack - Store - Sort - Trash - Restock 1.4.7]
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.2]
[Info   :   BepInEx] Loading [Build Camera 1.6.1]
[Info   :   BepInEx] Loading [StaminaSense 1.0.0]
[Info   :   BepInEx] Loading [XPortal 1.2.20]
[Info   :Jotunn.Main] Initializing GUIManager
[Info   :Jotunn.Main] Initializing InputManager
[Info   :Jotunn.Main] Initializing MinimapManager
[Info   :Jotunn.Main] Initializing PrefabManager
[Info   :Jotunn.Main] Initializing AssetManager
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Privilege Multiplayer is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] Privilege UserGeneratedContent is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] Privilege CrossPlay is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] 05/16/2024 14:12:53: Set background loading budget to Low
[Info   : Unity Log] TreeRespawn Loaded 6 seeds from D:\SteamLibrary\steamapps\common\Valheim\BepInEx\plugins\TreeRespawn\tree_dict.json
[Info   :Jotunn.Main] Initializing LocalizationManager
[Warning: Unity Log] 05/16/2024 14:12:53: Fetching PlatformPrefs 'GuiScale' before loading defaults
[Warning: Unity Log] 05/16/2024 14:12:53: Fetching PlatformPrefs 'GuiScale' before loading defaults
[Info   : Unity Log] 05/16/2024 14:12:54: Starting to load scene:start.unity (169d7618616154c03be07e9ad3af5893)

---it has some steam ID stuff here that I'm taking out but can put the entire log if needed ---

[Warning:Jotunn.Utils.ModCompatibility] Client loaded additional mod: XPortal

One last piece of information. When I try to login and get kicked out. Jotunn reports that the server does not have Xportal 1.2.20 loaded. From the log reports it says it is so I'm at a loss

**Comment by SpikeHimself** [comment]
Hi @meltdown1970, I can confirm this is also happening when I run a dedicated server. It appears to be an issue with Jotunn. I've opened https://github.com/Valheim-Modding/Jotunn/issues/432 for it. Awaiting their feedback.

**Comment by SpikeHimself** [comment]
p.s. probably unrelated (maybe?), but your server seems to be running BepInEx 5.4.23, while the latest version for Valheim is 5.4.22

https://thunderstore.io/c/valheim/p/denikson/BepInExPack_Valheim/

**Comment by Datzju** [comment]
+1

**Comment by LMorgil** [comment]
I've got the same problem. It works just fine locally but it breakes down when you try to zun it on a server.

**Comment by SpikeHimself** [comment]
Hi @meltdown1970 @Datzju @LMorgil you can fix this issue by making a change to your BepInEx config file (located at `Valheim\BepInEx\config\BepInEx.cfg`).

At the very bottom you will find the section `[Preloader.Entrypoint]`. Under this section you will find a setting called `Type`. The value of this setting needs to be `GameObject` (**not** `Application`).

Please let me know if this was the case for you and if it did indeed fix the issue.

**Comment by keckstein14** [comment]
I'm still experiencing this issue, responded here:

https://github.com/Valheim-Modding/Jotunn/issues/432

**Comment by joegoldin** [comment]
> I'm still experiencing this issue, responded here:
> 
> [Valheim-Modding/Jotunn#432](https://github.com/Valheim-Modding/Jotunn/issues/432)

Welp, they closed your bug issue, but I'm seeing the same problem _and_ can confirm the BepInEx logs show it loading on my dedicated server. There are a few other Jotun-dependent mods I've had to remove for the same reason :(

**Comment by SpikeHimself** [comment]
I closed the issue myself because it was solved on my end. It's just a word. The jotunn devs have not abandoned it.

**Comment by meltdown1970** [comment]
Your fix worked for me. Thanks :)

**Comment by etonevozmojno** [comment]
@SpikeHimself huge thanks to you, works perfectly!!!
