### ISSUE TITLE
Ore Transport Allowance Once Biome Boss has been Killed By Player

### ISSUE THREAD

**Issue by Morpheus1101** [SpikeHimself/XPortal#104]
I've seen this in other portal mods, but basically for e,g, If a player kills The Elder, it would allow them to be able to Transport Copper, Tin & Bronze through the portal, same again once you deff each biome boss there after, BoneMass to Allow Iron etc etc

**Comment by SpikeHimself** [comment]
Hi @Morpheus1101 this is achieved by another mod titled "Advanced Portals". This mod is fully compatible with XPortal.
