### ISSUE TITLE
XPortal Dropdown isnt visible in VHVR 

### ISSUE THREAD

**Issue by Aceship** [SpikeHimself/XPortal#11]
XPortal Dropdown is not visible in VHVR
is it possible that the dropdown isnt on the right layer (UI layer) ?

(Note the top left is the non filtered UI placed on world, while the bottom right is the actual UI rendered for VR, which only allow show UI Layer)
![VirtualDesktop Android-20230206-093005](https://user-images.githubusercontent.com/5337323/216873196-3bc0f268-b89f-49eb-b8f2-5c2f38066761.jpg)

**Comment by SpikeHimself** [comment]
That's very odd. XPortal doesn't create the dropdown, it comes from the Jotunn library, which just uses the normal Unity dropdown element and then applies the Valheim styling to it. But I'll look into and see if I can find anything.

**Comment by SpikeHimself** [comment]
[XPortal-v1.2.1-issue-11.zip](https://github.com/SpikeHimself/XPortal/files/10662020/XPortal-v1.2.1-issue-11.zip)

Could you try with this test version?

**Comment by Aceship** [comment]
> [XPortal-v1.2.1-issue-11.zip](https://github.com/SpikeHimself/XPortal/files/10662020/XPortal-v1.2.1-issue-11.zip)
> 
> Could you try with this test version?

hmm apparently still doesnt work



> That's very odd. XPortal doesn't create the dropdown, it comes from the Jotunn library, which just uses the normal Unity dropdown element and then applies the Valheim styling to it. But I'll look into it and see if I can find anything.
> 
> Does this happen immediately after opening the UI? Or does it work first but then stops working when you change the destination for example?

it happens when i tried to open the dropdown, its just its not visible 


from what i checked, i tried changing the layer of this dropdown to UI and it works 
![image](https://user-images.githubusercontent.com/5337323/217003321-87195757-70bc-420f-8035-14b10b1b4a9d.png)

**Comment by Aceship** [comment]
> ```
> dropdown.GetComponent<Dropdown>().gameObject.layer = 5;
> ```
> 
> Strange that it doesn't work! I'll have to spend more time on this.

i think its supposedly the child of the `Dropdown` which is `Dropdown List`, instead of the dropdown itself, i tried changing layer of the `Dropdown` earlier and it doesnt work, it somehow needs to be the `Dropdown List`

**Comment by SpikeHimself** [comment]
[XPortal-v1.2.1-issue-11-a.zip](https://github.com/SpikeHimself/XPortal/files/10667845/XPortal-v1.2.1-issue-11-a.zip)

Good findings! Can you try this version and let me know if it's any better?

**Comment by Aceship** [comment]
> [XPortal-v1.2.1-issue-11-a.zip](https://github.com/SpikeHimself/XPortal/files/10667845/XPortal-v1.2.1-issue-11-a.zip)
> 
> Good findings! Can you try this version and let me know if it's any better?

This works nicely ! 
Thanks for the fix 👍

**Comment by SpikeHimself** [comment]
Thanks for the feedback @Aceship. You'll be happy to discover that I secretly included this in the latest release, v1.2.2 ;)
