### ISSUE TITLE
Wild beehives invincible after 1.2.1 update

### ISSUE THREAD

**Issue by DrTuSo** [SpikeHimself/XPortal#12]
Started this night a new world, new character and ran into the problem that I couldn't destroy wild beehives.
They don't take damage and, destroying the surrounding structure, lets them float in the air.
In my prior world, this was not an issue.
The only thing that changed, was the update yesterday. I spent nearly 7 hours trying to find out which mod was guilty and XPortal was the one, I had no clue it would bug the beehives. But as soon as I disabled the mod, the problem was gone.

**Comment by SpikeHimself** [comment]
That is very strange! I'll look into this. Thanks for reporting.

**Comment by DrTuSo** [comment]
Additional information. As soon as a wild beehive is bugged, it stays even if the world is loaded without any mods, full vanilla. That is the reason it took me so long to find the culprit. Creating a new world each time I had one of my mods deactivated and to find a wild beehive there.

**Comment by SpikeHimself** [comment]
Thank you for adding that. I can understand how it would have taken an age to find that, good effort on your part!! 

This is going to be a pain to debug :D

**Comment by SpikeHimself** [comment]
[XPortal-v1.2.1-issue-12.zip](https://github.com/SpikeHimself/XPortal/files/10662662/XPortal-v1.2.1-issue-12.zip)

Could you give this test version a go and let me know the results?

**Comment by Gotri1337** [comment]
same on my fresh server i was wondering what is wrong DrTuSo im gona test this in evening .

**Comment by DrTuSo** [comment]
Just got a very long sleep and with full energy I'm going to test the new version :) I'll report back later!

**Comment by DrTuSo** [comment]
With the map seed, the picture where the bees are, that was an easy and quick test.
Nothing in my setup changed, still 41 mods (now instead of 1.2.1 the test version, of course).
No mods updated.

All I can say -> Fixed! Tried 3 beehives and all broke without any problems with XPortal active and loaded (checked via BeepInEx console).

Awesome, thank you very much!

**Comment by SpikeHimself** [comment]
Fantastic! And just in time for today's release :)

Thank you for your assistance.

**Comment by DrTuSo** [comment]
Thank you for your great mod and great help 👍
