### ISSUE TITLE
Does XPortal Convert AnyPortal portal tags?

### ISSUE THREAD

**Issue by Vapok** [SpikeHimself/XPortal#13]
This is more of a question than a feature request, but the answer may result into a feature request.

We are currently using AnyPortal, and this mod sounds like a great upgrade to AnyPortal now that it's deprecated.

Will this mod convert existing portals that were tagged by AnyPortal?  Or will we have to go around and retag portals?

Second, unrelated question, does this mod work with Advanced Portals?  AnyPortal does, so I'm assuming you're not doing anything too crazy.  https://valheim.thunderstore.io/package/RandyKnapp/AdvancedPortals/

**Comment by SpikeHimself** [comment]
Hi! Thanks for your interest in XPortal.

> Will this mod convert existing portals that were tagged by AnyPortal? Or will we have to go around and retag portals?

AnyPortal and XPortal both use the same method of tagging that the vanilla game uses, so no extra work is needed. Your portal names will transfer without issue.

> does this mod work with Advanced Portals?

I have not received reports to state that it doesn't, but I haven't tested. So at this point, I don't know. If you would like to give it a go and let me know the results that would be greatly appreciated. And if you run into any problems I'll gladly take a look to see if there's anything I can fix.

**Comment by Vapok** [comment]
Hey Spike,

Confirmed, working great with Advanced Portals, and mod converted from AnyPortal just fine!

Thanks for the work on taking this up!  If you ever need anything come say hi at Vapok Gaming: https://discord.gg/VJw5nc4x

Thanks a bunch!

-Vapok
