### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by KarolWielki** [SpikeHimself/XPortal#14]
Could you remove **$piece_portal** where it is in the string together with **$piece_portal_tag**, it will make translation easier. Some languages have a different word order, and some even have a different charset.
```
~~$piece_portal~~ $piece_portal_tag
```
It would be good to leave more space for text on the left, the tag of the portal probably won't be that long.
![portal](https://user-images.githubusercontent.com/37109869/217663417-959a36f6-c32e-4d0d-b968-d322711249b1.PNG)

**Comment by SpikeHimself** [comment]
Thanks for the report!

I was thinking maybe I can resolve two issues with one fix here. How about instead of "Portal Name", the label just said "Name"? 

Then it doesn't include $piece_portal at all, **and** it will be smaller. Additionally, I don't have to ask all the other translators for new information.

For the dropdown label, you can leave out "Portal", so it only says "Destination". Then it's also shorter, and more in line with the translations that exist so far.

**Comment by KarolWielki** [comment]
I can't translate it only "destination" in Polish, in English translation it will be "Portal Destination" or "Point of Destination" in Polish both are too long :) I was looking for the best translation.

**Comment by SpikeHimself** [comment]
Understood. I will make the labels wider.

**Comment by SpikeHimself** [comment]
![image](https://user-images.githubusercontent.com/123466188/217671785-919d73bb-9003-4b5d-8b6c-0bb9cd5d9827.png)

Would this be acceptable?

**Comment by KarolWielki** [comment]
Portalu docelowego ;)

**Comment by SpikeHimself** [comment]
Oops, apologies!

How about this then?

![image](https://user-images.githubusercontent.com/123466188/217675784-a4c2ffa5-b5ec-4333-acc2-3ed6f4f1d97f.png)

**Comment by KarolWielki** [comment]
Nice, tnx

**Comment by KarolWielki** [comment]
xportal-translations-polish.json
```
{
  "piece_portal_description": "Łączy z innym Portalem",
  "piece_portal_settag": "Konfiguracja",
  "piece_portal_tag": "Nazwa Portalu",
  "piece_portal_target": "Portal Docelowy",
  "piece_portal_target_none": "(Brak Celu)",
  "piece_portal_tag_none": "(Bez Nazwy)",
  "hud_xportal_title": "Witaj, Podróżniku!"
}
```
xportal-translations-russian.json

```
{
  "piece_portal_description": "Подключается к другому порталу",
  "piece_portal_settag": "Конфигурация",
  "piece_portal_tag": "Имя Портала",
  "piece_portal_target": "Пункт Назначения",
  "piece_portal_target_none": "(Нет Цели)",
  "piece_portal_tag_none": "(Без Имени)",
  "hud_xportal_title": "Привет, путник!"
}
```

**Comment by SpikeHimself** [comment]
Thank you! I will include these translations in the next release (hopefully tomorrow).
