### ISSUE TITLE
Option to turn off Ping button

### ISSUE THREAD

**Issue by mjn666** [SpikeHimself/XPortal#17]
**Is your feature request related to a problem? Please describe.**
Not bug related. I'm setting up a challenge server with no mini-map, no map, no cartography table and _super_ limited portals. I like that you can just select a portal from a dropdown which is exactly what im after, but unfortunately having access to the Ping button allows people to peek the map.

**Describe the solution you'd like**
Just a simple toggle option to show/hide or enable/disable the Ping button would suffice.

**Describe alternatives you've considered**
Ive skimmed around some of the other popular portal mods out there and they often want to get too fancy with introducing new resources and what not which im just not interested in. So it seemed like a reasonable feature request for this mod instead, given the already simple UX which I like.

**Additional context**
N/A

**Comment by SpikeHimself** [comment]
This sounds like an easy enough addition, I'll see what I can do.

**Comment by SpikeHimself** [comment]
![image](https://user-images.githubusercontent.com/123466188/218551842-f2f4b11d-cfc6-48f4-bc14-bb543c1f8971.png)

This seems to do the job :)

**Comment by SpikeHimself** [comment]
Implemented in v1.2.4 which just went live :)

**Comment by mjn666** [comment]
Perfect, thank you!
