### ISSUE TITLE
This portal doesn't actually appear to exist. Heimdallr sees you...

### ISSUE THREAD

**Issue by TheBudds** [SpikeHimself/XPortal#18]
Latest version of xportal, gives that message when looking at the portal and any new one built.

Pressing F5 lets me see the error
[Error  :XPortal.Patches+TeleportWorldGetHoverTextPatch: This portal does not exist. Odin strokes his beard in confusion..

**Comment by SpikeHimself** [comment]
Hi, thanks for reporting! Could you please fill out the bug template? It will give me the information necessary to track down the cause of your issue.

**Comment by SpikeHimself** [comment]
@TheBudds  Friendly reminder that I cannot work on this issue without more details. Please provide additional information as laid out in the `Bug report` template.

If you have already resolved this issue yourself, by for example removing another mod which caused a conflict, please do let me know as well :)

**Comment by SpikeHimself** [comment]
I am closing this issue as I cannot work on it without more information. If you would like to provide the details that the bug report template asks for then I'd be happy to reopen it.
