### ISSUE TITLE
The idea of adding some features.

### ISSUE THREAD

**Issue by Taotaolxt** [SpikeHimself/XPortal#21]
Add restrictions to the original non-transferable items. (Configurable switches, preferably synchronized with the server)
For example, to teleport minerals (or other items that were restricted from being teleported in the original game), you need to spend the appropriate amount of gold or other freely configurable items (the amount consumed or depends on the teleport distance, or other conditions you deem reasonable).
If you don't have the appropriate consumable, you can't teleport.
I think free teleportation without restrictions would greatly shorten the life and enjoyment of the game, but simply not allowing players to teleport minerals is also a waste of time. Adding consumables is also a restriction on teleporting minerals. So I think this feature is still necessary.

**Comment by SpikeHimself** [comment]
Hi, thanks for your interest in XPortal!

At this moment XPortal's goal is to make it easier to choose a destination portal when you want to travel. 

XPortal does nothing with items or costs and it does not check if a player or their inventory is teleportable or not. There are plenty of other mods that offer such functionality, like "Valheim Plus" or "Teleport Everything". As such I don't see the added value in adding this to XPortal, as XPortal is, to my knowledge, fully compatible with those mods.
