### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by Mxfuuu** [SpikeHimself/XPortal#23]
**Describe the bug**
I manually added XPortal using BepInEx, however I do not think the plug in was added to my game.

**Version**
XPortal v1.2.5

**Environment**
* Singleplayer on Linux, specifically Nobara 37 which is a unofficial fork of Fedora

**Other mods**
I am using Unrestricted Portals, and it works fine.

**Priority**
* High (XPortal does not work at all anymore)

**Additional information**
Add any addtional information here. Anything that you think might help is appreciated.

**Comment by SpikeHimself** [comment]
Hi, thanks for reporting! 

Please attach your `LogOutput.log` so that I can see what's going wrong.

**Comment by Mxfuuu** [comment]
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/10788110/LogOutput.log)

Here you go!
I made some changes 20-30 mins ago to the config file after checking your comments on the other issues reported here.

**Comment by SpikeHimself** [comment]
Great!

On line 21 you will find the cause of your issue:

    [Error  :   BepInEx] Could not load [XPortal 1.2.5] because it has missing dependencies: com.jotunn.jotunn

XPortal relies on Jötunn. You can download Jötunn from:
- [Thunderstore](https://valheim.thunderstore.io/package/ValheimModding/Jotunn/)
- [Nexus Mods](https://www.nexusmods.com/valheim/mods/1138)
- [GitHub](https://github.com/Valheim-Modding/Jotunn/releases)

I did not state this clearly in the installation instructions, so I get why you might have missed this. I will update those instructions soon.

Please let me know if installing Jötunn does indeed fix your problem :)

**Comment by Mxfuuu** [comment]
it worked! however the UI seems different from the one in the main page. 
![image](https://user-images.githubusercontent.com/101470404/220211216-67eb51a2-ef5f-445c-9dc3-8a512a3546f2.png)

**Comment by SpikeHimself** [comment]
That looks like you didn't include the translation files when you installed, or maybe put them in the wrong place. The `Translations` directory should sit next to `XPortal.dll` inside `Valheim\BepInEx\plugin\XPortal\`

**Comment by Mxfuuu** [comment]
That's exactly how I placed the files. However there is something wierd happening with the Translations directory. I have to use admin rights every time to access the folder/files in the directory.
![Screenshot from 2023-02-21 06-00-32](https://user-images.githubusercontent.com/101470404/220215337-64c5b6e2-5561-424d-a7cb-bc1473f59027.png)
![Screenshot from 2023-02-21 06-00-43](https://user-images.githubusercontent.com/101470404/220215342-95814536-4cd9-492a-b753-15dbd137716e.png)

**Comment by Mxfuuu** [comment]
I had to change the folder permissions in order for it to work.

From this 
![Screenshot from 2023-02-21 06-06-27](https://user-images.githubusercontent.com/101470404/220216183-4e77f8dc-7301-452a-a0f8-0bc4df163e25.png)
to this
![Screenshot from 2023-02-21 06-13-15](https://user-images.githubusercontent.com/101470404/220216199-fd38c6f8-9e7e-4b80-843c-5d34127e8633.png)

**Comment by Mxfuuu** [comment]
thank you for the help!

**Comment by SpikeHimself** [comment]
That would solely be an issue in your OS I'm afraid. I build the package on Windows so I have no control over what permissions are set when it is installed on Linux.

Glad you got it working!
