### ISSUE TITLE
Request - Config option to double portal crafting cost

### ISSUE THREAD

**Issue by steelstiletto** [SpikeHimself/XPortal#24]
**Is your feature request related to a problem? Please describe.**
XPortal mod makes portal pairs essentially cheaper by only requiring installation of a new portal on one side.

**Describe the solution you'd like**
Option to double the crafting cost of portals.

**Describe alternatives you've considered**
Other options would be a configurable build cost for the portal

**Comment by SpikeHimself** [comment]
Hi, thanks for your request!

I agree with you that XPortal is essentially a cheat, in that it makes portals cheaper. Have you looked at [Recipe Customization](https://www.nexusmods.com/valheim/mods/1245) by aedenthorn? From the looks of things this mod might be able to achieve exactly what you're looking for, and if I don't have to reinvent the wheel, I'm all for it ;)

I'm going to leave this request open either way though, as I do think it might be a suitable addition to XPortal.

**Comment by steelstiletto** [comment]
I got a similar recommendation from asking on the Valheim official discord, they suggested I use a mod called Wacky's Database. I'm using it to fulfill this purpose now, so this is really low prio for me. In case anyone else after me wants to use Wacky's Database for a similar purpose, the command to generate a config file for portals in that mod is: 

wackydb_save_piece portal_wood

Once the file is generated, it's really simple to modify the recipe cost.

Thanks for considering the request though! I'll keep an eye out for future updates, maybe I'll be able to prune Wacky's Database from my modlist if this is implemented :)

**Comment by SpikeHimself** [comment]
Hi @steelstiletto, I have just released v1.2.8 which includes your request!
