### ISSUE TITLE
Xportal key binds missing - valheim plus

### ISSUE THREAD

**Issue by bjbeare** [SpikeHimself/XPortal#26]
**Describe the bug**
I used vortex to install Xportal to a working valheim+ installation. When I create a new portal, the screen shows a poorly formatted error message that the key binding is missing. Portals work but the Xportal functionality can't be accessed. I can't find the configuration file for the mod.

**To Reproduce**
Install Valheim+, Install Xportal, Create a Portal. Configure the portal.

**Expected behavior**
Xportal menu should be exposed by Xbox buttons (running Xbox  controller with a PC install).

**LogOutput file(s)**
Please have `Debug` output enabled. Attach the file called `LogOutput.log` which can be found in the directory `Valheim\BepInEx\`.
If you play on a server, include the server's `LogOutput.log` as well.

**Version**
1.2.5

**Environment**
Single Player, PC

**Other mods**
Picture from Vortex appended.

**Priority**
High

**Additional information**
Add any addtional information here. Anything that you think might help is appreciated.

![Screenshot 2023-02-28 082928](https://user-images.githubusercontent.com/1189877/221916317-5a9d8567-e0fc-4e1c-b6b5-3f8cb6c20705.png)

![Screenshot 2023-02-28 083336](https://user-images.githubusercontent.com/1189877/221917452-55ca09cd-0896-48f2-857d-81e55a702f40.png)

[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/10852601/LogOutput.log)

**Comment by bjbeare** [comment]
log file with debug output enabled...
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/10852635/LogOutput.log)

**Comment by SpikeHimself** [comment]
Hi, thanks for reporting!

According to your logfile, XPortal was never even loaded into your game.

On line 3242 of your logfile, you will find this text:

    [Error  :   BepInEx] Could not load [XPortal 1.2.5] because it has missing dependencies: com.jotunn.jotunn

This means that you did not install Jötunn. Without Jötunn, XPortal cannot be used.

This is also mentioned in the XPortal requirements on Nexus Mods:

![image](https://user-images.githubusercontent.com/123466188/221919574-c6fdb1a4-e556-4479-97e1-157e8e5aae17.png)

As well as on XPortal's description page under "Installation instructions":

![image](https://user-images.githubusercontent.com/123466188/221919765-6cf08fa5-7319-4b6c-8e19-4951c87cbb68.png)

You can download Jötunn from:
- [Nexus Mods](https://www.nexusmods.com/valheim/mods/1138)
- [Thunderstore](https://valheim.thunderstore.io/package/ValheimModding/Jotunn/)
- [GitHub](https://github.com/Valheim-Modding/Jotunn/releases)

**Comment by bjbeare** [comment]
I thought that vortex would take care of all dependencies! Trying it now

**Comment by bjbeare** [comment]
User error. TY for a fantastic mod!

**Comment by SpikeHimself** [comment]
> I thought that vortex would take care of all dependencies! Trying it now

I wish! It would make a lot of sense if it did, since the dependencies are right there on Nexus. Sadly you have to take care of this manually :)
