### ISSUE TITLE
(BUG) Error after portal useage once, as host.

### ISSUE THREAD

**Issue by Crescent-Eclipse** [SpikeHimself/XPortal#3]
As a host of my server, i got rid my portal hub and built a new system, Apon using the portal once to travel to a destination and back, i am unable to to configer the portal anymore and my console spits out this error code.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
XPortal.XPortalUI.PopulateDropdown () (at <eb5284e3cfa74cbd8f1ab1e80cd23f69>:0)
XPortal.XPortalUI.ConfigurePortal (XPortal.KnownPortal portal, System.Collections.Generic.Dictionary`2[ZDOID,XPortal.KnownPortal]& knownPortals) (at <eb5284e3cfa74cbd8f1ab1e80cd23f69>:0)
XPortal.XPortal.OnPostPortalInteract (ZDO portalZDO) (at <eb5284e3cfa74cbd8f1ab1e80cd23f69>:0)
XPortal.HarmonyPatches+TeleportWorldInteractPatch.Postfix (ZNetView& ___m_nview, System.Boolean& __result) (at <eb5284e3cfa74cbd8f1ab1e80cd23f69>:0)
(wrapper dynamic-method) TeleportWorld.DMD<TeleportWorld::Interact>(TeleportWorld,Humanoid,bool,bool)
Player.Interact (UnityEngine.GameObject go, System.Boolean hold, System.Boolean alt) (at <35c0f7aa1999477788815a7bf78200d7>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

My Clients, are able to use the portal just fine.
deleteing and building a new portal works, but then after use im locked out again.
let me know if you need any more info! illdo my best to provide

**Comment by SpikeHimself** [comment]
Hi, thanks for reporting!

Just to double check: You are running the game while hosting, correct? You are not running a dedicated server?

Does the same thing happen if nobody else is in your game? 

Could you enable debug logging and send the whole BepInEx output logfile? 
You can enable this in `Valheim\BepInEx\config\BepInEx.cfg` by changing the value of `LogChannels` to `Info, Warn, Error, Debug`
The logfile is located here: `Valheim\BepInEx\LogOutput.log`

**Comment by SpikeHimself** [comment]
[XPortal-v1.0.1-issue3.zip](https://github.com/SpikeHimself/XPortal/files/10558852/XPortal-v1.0.1-issue3.zip)

I think I already found the problem. Can you try with this debug version, and let me know the results?

**Comment by Crescent-Eclipse** [comment]
i was just restarting to get a fresh log, But ill try this. Thank you for the fast response time!

**Comment by Crescent-Eclipse** [comment]
My pleasure, I am glad for this mod, my base was really starting to tank everyones frames with the 20 portals haha.
