### ISSUE TITLE
Ping Button still not working in 1.2.8 Release

### ISSUE THREAD

**Issue by KvitravnBelial** [SpikeHimself/XPortal#35]
**Describe the bug**
* We updated the XPortal but the Ping Button is still not working 

**LogOutput file(s)**
* (for future reference, you can attach a file to a comment by dragging it onto the textbox, you don't have to paste the contents)
* Server has no Errors while using Ping Button only Client

**Version**
* 1.2.8

**Environment**
* Multiplayer Client (I joined another server/host)

**Priority**
* Medium

**Comment by SpikeHimself** [comment]
Thanks for reporting. It appears I did a dumb. New version coming asap!

**Comment by SpikeHimself** [comment]
Hi @KvitravnBelial, I have just released v1.2.9 which fixes this issue.
