### ISSUE TITLE
Handling of input from on-screen keyboard

### ISSUE THREAD

**Issue by SpikeHimself** [SpikeHimself/XPortal#4]
From Nexus Mods:

> There's an issue with this mod in VHVR.  In VHVR when I click a portal it brings up the portal configuration window and a virtual keyboard to change its name.  When I click done on that keyboard it automatically closes the portal configuration window so I can't choose a destination or ping or anything.  The keyboard hides the portal config window and prevents interacting with anything else so I have to close it.  It's likely built-in to VHVR to close the default portal window when done typing.  Since AnyPortal made its own window it doesn't have this problem and is still usable.  A possible fix is to not automatically have it activate the text box for the portal's name so the virtual keyboard doesn't come up.

**Comment by SpikeHimself** [comment]
XPortal reacts to an Enter keypress to "submit" the portal configuration window. So the normal normal behaviour is that you type in the portal name and then press Enter, which submits your changes and closes the window. This is a key behaviour to intuitive UI interaction IMO, and should not be changed.

We can tackle this if it were possible for XPortal to detect that an on-screen keyboard is being used, but I presume the keyboard exists outside of the Valheim instance. The game is simply being sent keypresses as though they came from a hardware keyboard.

An alternative approach could be to introduce a config option which disables "submit on enter", so that the user can choose how the UI behaves.

**Comment by Aceship** [comment]
Actually its more to VHVR bug, hence i added an option which fix this issue (https://github.com/brandonmousseau/vhvr-mod/commit/f8d96806d8305aa2d42465fbfc56d6d1301c2a54) , while its not released yet, it should works with XPortal and other stuff that have compatibility issue with automatically show keyboard

(note that it needs to be false to make the XPortal usable, but it still defaults on true)
![image](https://user-images.githubusercontent.com/5337323/217115576-bd11bef2-21f1-45df-a5c9-d855a7512fef.png)

**Comment by SpikeHimself** [comment]
That is awesome, thanks for your input on this @Aceship !

**Comment by SpikeHimself** [comment]
Fixed as per v0.9.7 of VHVR: https://github.com/brandonmousseau/vhvr-mod/releases/tag/v0.9.7
