### ISSUE TITLE
Possible bug with "ghost" portals

### ISSUE THREAD

**Issue by hsramm** [SpikeHimself/XPortal#43]
**Describe the bug**
Portals that get a name and later get destroyed leave a "(No Name)" until server reset.

**To Reproduce**
A buddy of mine says this doesn't happen to him but when I create a portal, give it a name, teleport to town, teleport back, break it down for mats, it renames it (No Name) and doesn't go away until the server is restarted.

**LogOutput file(s)**
Same with the list of mods used, I don't have a ton of time right now to upload a log but can if that's really required and when able.

**Version**
1.2.10

**Environment**
Choose from the following options where you are experiencing the problem (leave only the ones you know about):
* Dedicated server
* Multiplayer Client (I joined another server/host)

**Other mods**
I'm not sure if I experience it without any other mods, my buddy is running the exact same mods I am and it's quite a bit and doesn't get the issue so not really sure if you really want me to list them all. I can if that really might solve it though.

**Priority**
Estimate how important this problem is. Choose Medium if you don't know.
* Medium (XPortal kind of still works, but it's not pleasant to use)

**Comment by hsramm** [comment]
![image](https://user-images.githubusercontent.com/36422849/235317450-bd84bc3e-a54a-426e-bab2-c3b14044df0d.png)

Is it somewhere else? Do you need my LogOutput.log file?

**Comment by hsramm** [comment]
![image](https://user-images.githubusercontent.com/36422849/235333993-1525255a-508e-4477-8a14-a53ee0eb4611.png)
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/11360509/LogOutput.log)

**Comment by SpikeHimself** [comment]
Sorry, I was travelling when I wrote my previous comment, hence the brevity.

Please see here how to enable debug logging: https://github.com/SpikeHimself/resources/wiki/BepInEx:-Enable-debug-logging

**Comment by hsramm** [comment]
No problem, you are good! Also the list of mods:

AAA_Crafting
aedenthorn_MapCoordinatesDisplay
AutomaticFermenters
AutomaticFuel
AutoRepair
AzuHoverStats
AzuMiscPatches
BetterArchery
BetterArcheryEAQSFix
BetterNetworking_Valheim
BetterUI_Reforged
Blacksmithing
Blacksmiths_tools
Building
Build_Camera_Custom_Hammers_Edition
ComfigWatcher
ComfortTweaks
Compass_By_Aedenthorn
ConversionSizeAndSpeed
CookingStationTweaks
CraftFromContainers
CreatureLevelAndLootControl
Deds_Army
Display_Day_and_Time_in_HUD
Enhanced_Bosses_Redone
Enhuddlement
EpicLoot
EpicValheimsAdditions
EquipmentAndQuickSlots
Evasion
Farming
Foraging
GapFiller
GracefulLanding
Groups
GumshoeTimerSuite
Heightmap_Unlimited_Remake
HoneyPlease
HoneyPlus
HookGenPatcher
Infinity_Hammer
InstantEquip
InstantMonsterLootDrop
Jotunn
Judes_Equipment
LevelingSystem
Lumberjacking
MinimalStatusEffects
Minimal_UI
Mining
MonsterLabZ
More_and_Modified_Player_Cloth_Colliders
MultiUserChest
No_Food_Degradation
OdinHorse
OdinsSteelworks
OdinTrainingPlace
Official_BepInEx_ConfigurationManager
PassivePowers
PlanBuild
PlantEverything
PotionPlus
QuickConnect
QuickTeleport
Quick_Stack_Store_Sort_Trash_Restock
Ranching
RecyclePlus
ReliableBlock
Sailing
Sarcen_FarmGrid
SeedTotem
ServerSideMap
Server_devcommands
ShieldMeBruh
Skittering_Madness
SmoothSave
SortCraft
Spawn_That
Teleport_Instantly_Updates_Weather_And_Removes_Wet_Debuff
ToggleMovementMod
UnderTheRadar
UnrestrictedPortals
ValheimCuisine
VikingsDoSwim
World_Edit_Commands
XPortal :)

I will post the log file when I come across the bug but there is a comprehensive list of my mods for now at least.

**Comment by SpikeHimself** [comment]
Thank you. The logfile is the key here so I'll wait for that :)

**Comment by hsramm** [comment]
My apologies, I had built a new computer and got pre-occupied with work. Here is the log file after making a portal, breaking it down, setting up a new one, and seeing (No Name) on the porta list.

[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/11392107/LogOutput.log)

**Comment by hsramm** [comment]
That might have been on a character that didn't have the debug settings, if that didn't contain the information you needed...let me know and I'll try again.

**Comment by SpikeHimself** [comment]
If you just built a new PC you'll have the default settings again - so yep you need to enable debug logging once more, sorry!

**Comment by hsramm** [comment]
No problem! Might be a few days but working on it...lol -.-

**Comment by hsramm** [comment]
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/11410774/LogOutput.log)

I saw someone else's (No Name) but I tried to click on it to teleport to it and ya, here's the log. Hoping it contains what you need!

**Comment by SpikeHimself** [comment]
Thanks!

> I saw someone else's (No Name) but I tried to click on it to teleport to it

I see nothing wrong in the logfile you just shared, but as stated previously I think the bug might occur at the moment of the portal being removed. If it had already happened before you joined, then this won't have appeared in your log file.

To get the information I need to resolve this, I need a logfile where you have reproduced the issue, so that I can see what goes wrong.

**Comment by hsramm** [comment]
Ok there we go, hope you can find what you're after. I noticed when I clicked on the (No Name) it would say "TRIGGER" in the BepInEx command window.

[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/11413921/LogOutput.log) (Mine)
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/11413922/LogOutput.log) (Server)

**Comment by hsramm** [comment]
I haven't seen anything in the log to indicate an error, even in a solo playthrough...there are a bunch of (No Name) portals and they can be pinged (based on where they were) as if they were still there and active.

![image](https://github.com/SpikeHimself/XPortal/assets/36422849/5f683f60-c3bb-4f06-9ed1-65899494ac67)

**Comment by SpikeHimself** [comment]
Sorry for the slow response. Life happened.

Are you sure both those log files are from the same session?

In your client log I can see that you are trying to destroy portal "cop1", but in the server log this event is nowhere to be found.

**Comment by hsramm** [comment]
Yea, it should be. Right after it started occurring, I went and got the files for both the client and server right away. This even happens in single-player.

**Comment by SpikeHimself** [comment]
Very strange. Perhaps the server hadn't yet flushed the cache (i.e. the file wasn't written yet when you downloaded it). 

I did see an error in your server log, but I'm not sure if it's related (it mentions something called "Cozyheim", not sure what is).

If you also have the issue in single player, that makes it a lot easier, because then the server and client logs are in the same file. Could you try it in single player and send me the log of that?

Sorry that this is taking so long, it's a very strange issue.

**Comment by hsramm** [comment]
Sure, I can do that...I think the Cozyheim is the guy's name, he makes Leveling System and some other stuff.

**Comment by SpikeHimself** [comment]
Hopefully I can figure stuff out from the logfile, because the alternative is you having to disable/enable all your mods one by one to figure out where the conflict comes from, and that will not make anyone happy 😅

**Comment by SpikeHimself** [comment]
Hi @hsramm a new version has just gone live in which some changes were applied that may affect this issue. If you still encounter it let me know and we can continue working on this.

**Comment by hsramm** [comment]
Alrighty, looking forward to testing it at some point next week when I get back home. Thank you!
