### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by VasariRulez** [SpikeHimself/XPortal#44]
**Question 1: What is the name of the language you are translating to?**

Italian

**Question 2: Please replace the English translations in quotation marks below:**

1: Portal description: "Si connette ad un altro portale",
2: Set tag: "Configura",
3: Tag: "Nome",
4: Target: "Destinazione",
5: Target 'none': "(Nessuno)",
6: Name 'no name': "(Senza nome)",
7: XPortal UI header title: "Salute, viaggiatore!"

**Comment by SpikeHimself** [comment]
Thank you for your contribution! This will be included in the next release of XPortal.
