### ISSUE TITLE
Map of active portals

### ISSUE THREAD

**Issue by gacekssj4** [SpikeHimself/XPortal#45]
I saw anyportal mod https://www.nexusmods.com/valheim/mods/170 

It said its repalced by XPortal. Was wondering why it had map, and this has only ping.

It would be very handy to be able to see all portals on map.

Also, if clicking on map ping would set destination automatically, then it would be super awesome.

That would acually make game "dont care about portal names anymore"

**Comment by SpikeHimself** [comment]
I think you're looking for a mod called TargetPortal. That mod does pretty much what you're describing.

XPortal prefers to stay close to vanilla behaviour.

**Comment by gacekssj4** [comment]
Thank you.
