### ISSUE TITLE
Custom Meshes by Aedenthorn breaks XPortal UI

### ISSUE THREAD

**Issue by DrPhill94** [SpikeHimself/XPortal#47]
I made a bug report on the nexus page for [Custom Meshes](https://www.nexusmods.com/valheim/mods/184?tab=bugs) but seeing as it hasn't been updated since 2021 I'm not sure if Aeden is interested in messing with it. I don't know if it's something you could look into, nor do I think it is that important (I couldn't find anyone else having this issue) but I thought you might want to check it out, at least!

And here's a direct link to the [screenshot](https://imgur.com/gallery/kbj8ZgP) I included

**Comment by SpikeHimself** [comment]
I doubt I could do much about this, as I don't create any of this myself. All the UI stuff XPortal uses comes from Jotunn.

But if you would like to share your logfile I'd be happy to take a look and see if there's anything usable in there.

**Comment by DrPhill94** [comment]
No worries, I believe the problem is in Custom Meshes

Unfortunately I've been doing a lot of overhauling with our server since yesterday and the logs are gone, though when I looked through them myself there wasn't much coming through when interacting with your portal as you can see in the screenshot. Might have been my log filtering

I'll see if I can load up a vanilla profile later today and do it again, it's reproduceable with just JVL, XPortal, and Custom Meshes enabled so it won't take long

**Comment by SpikeHimself** [comment]
Hi @DrPhill94  did you get any further with this? If there is anything else I can do please feel free to reopen this issue.
