### ISSUE TITLE
Add option to skip the portal load animation 

### ISSUE THREAD

**Issue by insanity906** [SpikeHimself/XPortal#48]
Please add an option to skip the portal load animation to allow quicker teleportation? It would be much appreciated! :D

**Comment by SpikeHimself** [comment]
Hi, thanks for your suggestion.

There are already mods out there that do exactly this. I don't think it's necessary for XPortal to offer this functionality. It also feels a little out of scope: XPortal's core function is to provide an alternative interface to connect portals.
