### ISSUE TITLE
Portals not working : portals unamed and list gone

### ISSUE THREAD

**Issue by Quentin-ctrL** [SpikeHimself/XPortal#49]
Hi,

**Describe the bug**
Since the latest updates 0.216.9 portals list is gone and all portals are unamed.
Impossible to reconnect old portals and new portals doesn't seem to work either
No problem yesterday on windows 
Same behavior on 2 different maps

Removed Xportal mod and portals work as expected.

**To Reproduce**
Install latest Valheim updates

**Version**
Which version of XPortal are you experiencing your problem with?
latest

* Singleplayer (linux / not tested on windows)

**Other mods**

Unrestricted Portals 

[Message:   BepInEx] BepInEx 5.4.21.0 - valheim (03/28/2023 20:49:57)
[Info   :   BepInEx] Loading [Jotunn 2.11.7]
[Info   :   BepInEx] Loading [XPortal 1.2.10]
[Info   :   BepInEx] Loading [UnrestrictedPortals 1.4.2]

Do you experience the issue also when you do not have any other mods installed? If applicable, please provide the full list of mods that you are using.

**Priority**

* High (XPortal does not work at all anymore)

**Additional information**
I reinstalled all mods to be sure I have the latest version
Is may be related to "Jotunn the Valheim Library" or "BepInExPack Valheim"

After removed Xportal (linked 2 sets of portal) and reinstalled Xportal mod, the portal list seems to work correctly.
If you use portal even if you select a portal it goes the 'default' portal. Using the ping function show the correct location.

Advanced Portals mod has been updated today. I don't see commit on the git repo :/
but changelog says : 

> #### 1.0.4
>   * Updates for 0.216.9 Valheim

  '

**Comment by swietyy** [comment]
I have just installed the mod for the first time. I can rename the portal and i do see the list etc. mod loads without any trouble, but 
the portal doesn't lit up. Do you know what's the issue?

**Comment by PuterPro** [comment]
> I have just installed the mod for the first time. I can rename the portal and i do see the list etc. mod loads without any trouble, but the portal doesn't lit up. Do you know what's the issue? Windows

Make sure your cAptiliZation is right. :)
'Main Home' and 'main home' are not the same, it's the most common error.

**Comment by swietyy** [comment]
> > I have just installed the mod for the first time. I can rename the portal and i do see the list etc. mod loads without any trouble, but the portal doesn't lit up. Do you know what's the issue? Windows
> 
> Make sure your cAptiliZation is right. :) 'Main Home' and 'main home' are not the same, it's the most common error.

It's right for sure. The mod itself should teleport you from portal "a" to "b" anyways. If i call one of them "a" and set the destination to "b" it doesnt lit up. Neither if i call both of them "a" and "a". Everything seems to work, i can use "ping" to see specific portal on the map etc. but can't teleport to any of the places :D

**Comment by PuterPro** [comment]
> > > I have just installed the mod for the first time. I can rename the portal and i do see the list etc. mod loads without any trouble, but the portal doesn't lit up. Do you know what's the issue? Windows
> > 
> > 
> > Make sure your cAptiliZation is right. :) 'Main Home' and 'main home' are not the same, it's the most common error.
> 
> It's right for sure. The mod itself should teleport you from portal "a" to "b" anyways. If i call one of them "a" and set the destination to "b" it doesnt lit up. Neither if i call both of them "a" and "a". Everything seems to work, i can use "ping" to see specific portal on the map etc. but can't teleport to any of the places :D

Yep, read my Edit 2 update. It's just broken. :( Well, I tried, LOL! Cheers!

**Comment by Quentin-ctrL** [comment]
As a workaround to play Valheim until it's fixed. 
you can revert in steam the 'previous stable' and restore backup to make sure datas are not messed up. it worked for me.

Or you have to play old style and name both portals with the same name (good luck if you explored a lot and have 100x portals :)

**Comment by SpikeHimself** [comment]
Thanks for reporting everyone, I will look into this as soon as I can.

**Comment by cirkutninja** [comment]
Read through the other comments and didn't see anyone have problems loading their game. I try to load mine and it gets stuck loading forever. Looking at the log gives the following.

```
[Warning:Jotunn.EventExtensions] Exception thrown at event InvokeOnVanillaMapDataLoaded in XPortal.MinimapManager_OnVanillaMapDataLoaded:
System.MissingMethodException: long ZDOMan.GetMyID()
  at Jotunn.EventExtensions.SafeInvoke (System.Action events) [0x00018] in D:\Projects\Jotunn\JotunnLib\Extensions\EventExtensions.cs:26
```

**Comment by PuterPro** [comment]
YEA! Works **PERFECTLY**! You da Man, LOL 
Unless ... You da Girl ... :P 
Got my Portals all back, amazing response time, Thx SOOO much.

**Comment by Quentin-ctrL** [comment]
list of portals : OK
select portals and teleport : OK
but not saving destinations between logins,  see https://github.com/SpikeHimself/XPortal/issues/53

I'll try to check with Patch 0.217.4 – Hildir's Request.

**Comment by Quentin-ctrL** [comment]
Completely broken UI in Patch 0.217.4 – Hildir's Request.
Unable to select name or list.
Can't close UI and need to exit session :/
![Capture d’écran du 2023-06-17 02-09-30](https://github.com/SpikeHimself/XPortal/assets/70467477/50e117ea-3ad6-45de-bbca-0829d3edfaec)

Priority : High but it's public test 

tested on Singleplayer (linux) with latest Jotunn and XPortal version. Unrestricted portal should be useless with the new " World modifiers".

**Comment by SpikeHimself** [comment]
Thanks for the heads up @Quentin-ctrL - would you mind creating a new issue for that?

**Comment by SpikeHimself** [comment]
> Spike, are you on a discord that I can reach out to you on? My username is `@vapok_`

Hi @Vapok - sorry, I don't have discord. You can message me privately on Nexus and I can provide my email address there, if that's feasible for you.

**Comment by SpikeHimself** [comment]
Meanwhile we're 2 versions ahead of what issue was related to. Thanks for your support everyone. Please report any new problems in new issues.

**Comment by Quentin-ctrL** [comment]
> Thanks for the heads up @Quentin-ctrL - would you mind creating a new issue for that?

done : https://github.com/SpikeHimself/XPortal/issues/56
