### ISSUE TITLE
Possible conflict with Gungnir Console Enhancement Suite.

### ISSUE THREAD

**Issue by poncho558** [SpikeHimself/XPortal#5]
Game loads you into a void where you cant do anything if trying to play with both mods installed. Removing either XPortal or Gungnir resolves the issue. 

![Screenshot_20230201_030532](https://user-images.githubusercontent.com/68041259/216165506-3a0963ed-a5c9-4afd-abc2-9ef30ee48eb5.png)

**Comment by SpikeHimself** [comment]
Hi! Could you send the complete output logfile?

**Comment by SpikeHimself** [comment]
It's difficult to tell without more information, but it looks like Gungnir queries InventoryGui.IsVisible() earlier than what XPortal is expecting:

> https://github.com/zambony/Gungnir/blob/aea8ae997b21e8c780a5d8a25b71bd90356a422f/src/Gungnir.cs#L157

        void Update()
        {
            // Disable keybinds while in text inputs or menus.
            if (Console.IsVisible() ||
                (Chat.instance != null && Chat.instance.HasFocus()) ||
                TextInput.IsVisible() ||
                Minimap.InTextInput() ||
                Menu.IsVisible() ||
                InventoryGui.IsVisible())
                return;

.. and XPortal (in a previous version) started building its UI at this point.

Commit 3897095ed91da62fc59b760915749c7babda1bfe which was included in v1.1.0 should have fixed this.

**Comment by poncho558** [comment]
Hi, sorry for the late reply. Honestly, I don't understand code at all.
Sorry I can't be of any help, the screenshot I attached in the original
post was the error that kept repeating itself.

**Comment by SpikeHimself** [comment]
Don't worry about the code @poncho558 ;) The important part of my last comment was:

>  v1.1.0 should have fixed this

If that's not the case I'd love to hear it!
