### ISSUE TITLE
Opening portal menu after using cultivator blocks you from doing anything.

### ISSUE THREAD

**Issue by SuperMakine** [SpikeHimself/XPortal#51]
**Describe the bug**
Opening portal menu after using cultivator blocks you from doing anything. You have to force quit Valheim and open it to be able to do anything.

**To Reproduce**
1. Use cultivator. Plant something.
2. Open portal menu.
3. Done. Should be stuck now.

**Expected behaviour**
No idea. It kept spamming the same error.

**LogOutput file(s)**
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/11739804/LogOutput.log)

**Version**
1.2.11

**Environment**
* Multiplayer Host (my game is the server)
* Multiplayer Client (I joined another server/host)
* Singleplayer

**Other mods**
I didn't try without other mods, here is my mod list:

denikson-BepInExPack_Valheim-5.4.2105
Digitalroot-Better_Trader_Remake-2.2.10
Smoothbrain-DualWield-1.0.7
Smoothbrain-Sailing-1.1.5
aedenthorn_mods-InstantMonsterLootDrop-0.5.0
RandyKnapp-EquipmentAndQuickSlots-2.1.6
Smoothbrain-Foraging-1.0.4
Fu-CookingStationTweaks-0.4.1
Smoothbrain-CreatureLevelAndLootControl-4.5.6
Smoothbrain-Mining-1.1.4
ASharpPen-This_Goes_Here-2.1.1
Smoothbrain-Farming-2.1.8
castix-FloatingItems-1.0.0
LVH-IT-UseEquipmentInWater-0.2.3
ValheimModding-Jotunn-2.12.0
SpikeHimself-XPortal-1.2.11
xAfflict-UnrestrictedPortals-1.4.2
Smoothbrain-StaminaRegenerationFromFood-1.5.3
Azumatt-Official_BepInEx_ConfigurationManager-18.0.0
k942-MassFarming-1.6.0
ArmchairSavages-CropReplant-1.0.2
cdymrtn-BuildRestrictionTweaks-0.3.0
Smoothbrain-Blacksmithing-1.2.3
Smoothbrain-Cooking-1.1.12
NexusReUploadByPan-MiningMod-1.0.0
OhhLoz-HoneyPlus-5.2.0
Frogger-JustNoRoof-0.0.6
Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock-1.3.10
GemHunter1-FastTeleport-1.1.0
Advize-PlantEverything-1.13.6
Mydayyy-ServerSideMap-1.3.7
blacks7ar-MagicPlugin-1.5.4
Therzie-Warfare-1.4.5
Crystal-DeathPenalty-1.0.4
UnJohnny-Outsiders-1.5.3
MonsterLabZ-MonsterLabZ-3.0.1
Therzie-Armory-1.0.5
Therzie-Monstrum-1.1.1
aedenthorn_mods-AutoFuel-1.1.0

**Priority**
* Medium (XPortal kind of still works, but it's not pleasant to use)

**Additional information**
Add any addtional information here. Anything that you think might help is appreciated.

**Comment by SpikeHimself** [comment]
Hi @SuperMakine, thank you very much for reporting this issue.

I have just released v1.2.12 which fixes this problem.
