### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by hannahdevs** [SpikeHimself/XPortal#52]
**Describe the bug**
Infinite loop of `Null Reference Exception` causes world to slow until unplayable.

**To Reproduce**
Level ground with a hoe.

**LogOutput file(s)**
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
XPortal.Patches.Piece_SetCreator.CheckWearNTearCreationTime (System.Boolean delayed) (at <f92d2cd1b1fe4c0888553264fc479679>:0)
XPortal.QueuedAction.Trigger () (at <f92d2cd1b1fe4c0888553264fc479679>:0)
XPortal.QueuedAction.Update () (at <f92d2cd1b1fe4c0888553264fc479679>:0)
XPortal.XPortal.Update () (at <f92d2cd1b1fe4c0888553264fc479679>:0)
```
This error loops until the game is quit.

**Version**
1.2.11

**Environment**
* Dedicated server

**Other mods**
* Auto_Feed
* BeastsOfBurden
* Clock
* FastTeleport
* Item_Stand_All_Items
* Jotunn
* Keezys_Better_Wolves
* MultiCraft
* MultiUserChest
* PlantEasily
* PotteryBarn
* Quick_Stack_Store_Trash_Restock
* Quiet Portals
* SkillLossMod
* TeleportEverything
* ValheimCreativeMode

**Priority**
* Medium (XPortal kind of still works, but it's not pleasant to use)
Possibly critical? I'm not sure if what is happening can cause corruption.

**Additional information**
I know I am running many mods, but the error is referring to an XPortal specific function, so I don't think it is an incompatibility.

**Comment by SpikeHimself** [comment]
Hi @hannahdevs, thank you very much for reporting this issue.

I have just released v1.2.12 which fixes this problem.
