### ISSUE TITLE
MonoMod.Backports error during startup

### ISSUE THREAD

**Issue by ersan** [SpikeHimself/XPortal#55]
Error during startup with XPortal 1.2.12:
```
[Info   :   BepInEx] Loading [XPortal 1.2.12]
FileNotFoundException: Could not load file or assembly 'MonoMod.Backports, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at XPortal.XPortal.Awake () [0x00000] in <97a7626f7d8140998e9d84c6863f514a>:0
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.GameObject:.cctor()
UnityEngine.UI.Graphic:CacheCanvas()
UnityEngine.UI.Graphic:get_canvas()
UnityEngine.UI.Image:OnCanvasHierarchyChanged()
```

Does not occur in XPortal 1.2.11

**Comment by SpikeHimself** [comment]
Apologies, this has slipped in with the update of dependencies in the current version, however, for me it does not stop the game from functioning. You should be able to ignore the error for now. I will address this in the next version.

**Comment by ersan** [comment]
It stops the config file from being created if there isn't one, I'm not sure what other issues it may cause because I didn't do any further testing.

**Comment by SpikeHimself** [comment]
In that case I will prioritise a hotfix release.

**Comment by ukorn** [comment]
Hi,
thank you for this great mod.

Here on my dedicated Server, running in docker, XPortal stops working at all after the update to 1.2.12. The Game is running, but all Portals act like the vanilla ones.

Greetings

**Comment by SpikeHimself** [comment]
@ersan I have released  v1.2.13 as a hotfix to  v1.2.12. Please let me know if it works now.

**Comment by SpikeHimself** [comment]
@ukorn This sounds like a separate problem. If v1.2.13 does not fix it for you, please create a new issue.

**Comment by ersan** [comment]
> @ersan I have released v1.2.13 as a hotfix to v1.2.12. Please let me know if it works now.

It created the config file and there's no error now.

**Comment by ukorn** [comment]
all portals are working again, also no error in log, thank you

**Comment by SpikeHimself** [comment]
Thanks for the feedback both!
