### ISSUE TITLE
Stone Portals lose their names (and thus their destinations) each session

### ISSUE THREAD

**Issue by bonesbro** [SpikeHimself/XPortal#59]
**Describe the bug**
Stone Portals (https://valheim.thunderstore.io/package/JereKuusela/Stone_Portal/) reset to blank names when you load the game.  They also lose their link to the other portal and cannot be used, probably due to the same issue.

**To Reproduce**
Install the Stone Portals mod and create two of them; next to one another is fine.  Give them both a name and set their destinations to each other.  Quit and reload the game and observe that neither portal is linked anymore.

**LogOutput file(s)**
Please have `Debug` output enabled. Attach the file called `LogOutput.log` which can be found in the directory `Valheim\BepInEx\`.
If you play on a server, include the server's `LogOutput.log` as well.

**Version**
1.2.13

**Environment**
Only tested in singleplayer so far

**Other mods**
Large list, see lines 44-167 in attached Player.log

**Priority**
Estimate how important this problem is. Choose Medium if you don't know.
* High (XPortal does not work at all anymore)

**Additional information**
My first guess is that it's the change to XPortal.cs:321 in https://github.com/SpikeHimself/XPortal/commit/556b3840d972932a0490788855b153221d7e63d3.  I'm going to get my local repo working again and fiddle around with reverting that part.

It's also possible that Stone Portals itself is outdated and no longer registers itself correctly or fails to properly save its portal name.  It was last updated in December 2022.

[Player.log](https://github.com/SpikeHimself/XPortal/files/11963361/Player.log)

**Comment by bonesbro** [comment]
Stone Portals itself seems broken right now.  Without XPortal installed the stone portals don't link up with one another.  I'll send the bug report over to Jere.

**Comment by bonesbro** [comment]
Ok - after fixing Stone Portals mod itself, I'm still having a few problems with XPortals.  One of the two portals in each link seems to lose its target whenever you quit and restart the game.  The targets can be reset fine, and afterwards they work normally during the session, but one of the two loses its target (but not its tag) when starting a new session.  They keep their tags so it's pretty easy to work around.  I've attached the debug logs from both attempts, along with notes about what actions I took at each step.

Right now I'm going to do a bit more testing on my fix to Stone Portals itself before sending a PR to get it fixed.  I know that you can't do anything to address this issue at the moment until that fix comes out.
[XPortal_plus_StonePortal_notes.txt](https://github.com/SpikeHimself/XPortal/files/11972799/XPortal_plus_StonePortal_notes.txt)

**Comment by Quentin-ctrL** [comment]
Hi, 

It seems that's the same behavior I have described in https://github.com/SpikeHimself/XPortal/issues/57
I never used Stone portals but the destinations is not saved between sessions as well. 

I'm singleplayer also. I created another character but with wards it's very difficult to test.
The new character doesn't to suffer the issue (from few tests). I played back with the former character and it's all reset.

Hildir's Request is still in active development but no changelog mentioning portals issue.

**Comment by SpikeHimself** [comment]
Hi all. This is indeed the same issue as #57 - sadly I have not yet had time to give this the attention it needs, and so I have not been able to find a fix yet. I hope to find more time in the near future so I can address this. Apologies for the inconvenience.

**Comment by SpikeHimself** [comment]
I've delved into this issue further and have to take back what I said. I've fixed portal connections in the next version (release in a few minutes after typing this), but the stone portal ZDOs are indeed not picked up as per your previous description, because Valheim removed the `GetAllZDOsWithPrefab` functionality. To be continued..

**Comment by SpikeHimself** [comment]
Hi @bonesbro, I've started looking into this properly, and luckily found quickly that https://github.com/JereKuusela/valheim-stone_portal/pull/3/commits/7548eaaf1b9433f2c90d8968b16a866a752bbc78 has already addressed this issue. I'm not currently experiencing the issue where stone portal connections are lost (apart from another bug that is causing some portal connections to be lost, but that is not related to stone portals)
