### ISSUE TITLE
Focus transferred to Chat box after tagging

### ISSUE THREAD

**Issue by LyndonL37** [SpikeHimself/XPortal#62]
**Describe the bug**
* Post v1.2.14 update, when you name a tag: It brings up and places focus into the chat box after you press enter. I don't remember it doing that previously. 

**To Reproduce**
* Add or edit a portal tag, then press enter.

**Version**
* 1.2.14

**Environment**
* Dedicated server
* Multiplayer Client (I joined another server/host)

**Priority**
* Low (XPortal is still working fine, but sometimes a thing goes wrong)

Thanks for the good work on the quick update though. A great and indispensible mod!

**Comment by SpikeHimself** [comment]
Thank you for reporting, I will look into this as soon as I have more time.

**Comment by khui88** [comment]
Wanted to add something I believe relates to the focusing issue.

If you try to scroll through the destination list with your mouse scroll wheel, it will also affect character zoom. Dragging the side scrollbar doesn't affect the zoom.

Small annoyance, but honestly happy for the update earlier today. Also donation page gone?

**Comment by SpikeHimself** [comment]
Thanks for bringing that up @khui88, I'll see if I can find a way to deal with that.

Yes, 'buy me a coffee' removed my account for reasons I can't fathom and they failed to explain to me. In the mean time they have refunded all the donations I had received but not yet claimed. Quite annoyed with them.

**Comment by SpikeHimself** [comment]
I think this is the same issue as #64

**Comment by SpikeHimself** [comment]
This should be fixed by v1.2.15 which I released just a moment ago. Please let me know if you have any issues!
