### ISSUE TITLE
keystrokes for portal title also trigger actions

### ISSUE THREAD

**Issue by tdrury** [SpikeHimself/XPortal#64]
**Describe the bug**
When typing the name of a portal, if the name includes "m" the map comes up. I have hotkeys for my potions ("i", "o", "p") - if any of those letters are typed into the portal name, then I drink them. It seems keystrokes are not being consumed by the dialog and are propagating back into the game. I can still enter a name, a destination, ping, and click "ok" - all that works, but I'm going through potions very fast.

**To Reproduce**
Go to a portal and hit "e". Put the cursor in the Name field. Type a name that includes "m" - as soon as you hit "m" the map appears behind the dialog.

**Expected behaviour**
I should be able to enter a name without the keystrokes activating other things in the game.

**LogOutput file(s)**
Nothing in the logs

**Version**
1.2.14

**Environment**
* Singleplayer

**Other mods**
I wrote issue https://github.com/SpikeHimself/XPortal/issues/61 - all my mods are listed there.

**Priority**
Estimate how important this problem is. Choose Medium if you don't know.
* Medium (XPortal kind of still works, but it's not pleasant to use)

**Comment by SpikeHimself** [comment]
Hi @tdrury, thanks for reporting. This appears to be an issue in Jotunn, and I have logged https://github.com/Valheim-Modding/Jotunn/issues/407 with them as such.

**Comment by tdrury** [comment]
> Hi @tdrury, thanks for reporting. This appears to be an issue in Jotunn, and I have logged [Valheim-Modding/Jotunn#407](https://github.com/Valheim-Modding/Jotunn/issues/407) with them as such.

Thank you. I've subscribed to your issue on Jotunn.

**Comment by SpikeHimself** [comment]
I missed that update, glad to hear you got that sorted! XPortal has now also updated to specifically reference the new Jotunn version which officially solves this issue :)
