### ISSUE TITLE
Cursor disappears on activating Portal configuration.

### ISSUE THREAD

**Issue by turotulco** [SpikeHimself/XPortal#65]
**Describe the bug**
Installed the latest update, 1-2-14. Placed a Portal and pressed space to open configuration screen. My cursor disappeared and I could not activate either the text box or the dropdown. After pressing escape, the configuration did not disappear but the quit game screen appeared behind the configuration panel and was accepting keystrokes through the configuration panel.

**To Reproduce**
Place a portal, try to configure it.

**Expected behaviour**
I expected the configuration panel to function, it has for me in the past

**LogOutput file(s)**
(I could not locate how to turn on the Debug logging option. This is a copy and paste)

[Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2105 from Thunderstore
[Info   :   BepInEx] Running under Unity v2020.3.45.6687953
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.2.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 14 plugins to load
[Info   :   BepInEx] Loading [PlantEverything 1.11.5]
[Info   :   BepInEx] Loading [Clock Mod 1.4.3]
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Console and name InputText and parameters
[Warning:  HarmonyX] Unknown patch - Could not find method InputText with 0 parameters in type Console, but it was found in base class of this type Terminal
[Info   :   BepInEx] Loading [Show Container Contents 0.3.0]
[Info   :   BepInEx] Loading [Auto Map Pins 1.2.2]
[Info   :   BepInEx] Loading [MineableBarnacle 1.0.1]
[Info   :   BepInEx] Loading [Jotunn 2.12.6]
[Info   :    Jotunn] Initializing LocalizationManager
[Info   :    Jotunn] Initializing CommandManager
[Info   :    Jotunn] Initializing InputManager
[Info   :    Jotunn] Initializing SkillManager
[Info   :    Jotunn] Initializing PrefabManager
[Info   :    Jotunn] Initializing ItemManager
[Info   :    Jotunn] Initializing PieceManager
[Info   :    Jotunn] Initializing CreatureManager
[Info   :    Jotunn] Initializing ZoneManager
[Info   :    Jotunn] Initializing MockManager
[Info   :    Jotunn] Initializing KitbashManager
[Info   :    Jotunn] Initializing GUIManager
[Info   :    Jotunn] Initializing KeyHintManager
[Info   :    Jotunn] Initializing NetworkManager
[Info   :    Jotunn] Initializing SynchronizationManager
[Info   :    Jotunn] Initializing RenderManager
[Info   :    Jotunn] Initializing MinimapManager
[Info   :    Jotunn] Initializing UndoManager
[Info   :    Jotunn] Jötunn v2.12.6 loaded successfully
[Info   :   BepInEx] Loading [ClearTheAir 1.0.1.0]
[Info   :   BepInEx] Loading [Underwater 1.0.4.0]
[Info   :   BepInEx] Loading [PlanBuild 0.14.2]
[Info   :PlanBuild.Blueprints.BlueprintManager] Initializing BlueprintManager
[Info   :PlanBuild.Blueprints.BlueprintSync] Loading known blueprints
[Info   :PlanBuild.Plans.PlanManager] Initializing PlanManager
[Info   :   BepInEx] Loading [Valheim Plus 0.9.9.17]
[Info   :Valheim Plus] Valheim Plus full version: 0.9.9.17
[Info   :Valheim Plus] Trying to load the configuration file
[Info   :Valheim Plus] Found config file at: 'C:\Users\Owner\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Valheim\profiles\Default\BepInEx\config\valheim_plus.cfg'
[Info   :Valheim Plus] Loading config...
[Info   :Valheim Plus]
[Info   :Valheim Plus] [AdvancedBuildingMode] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [AdvancedEditingMode] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Armor] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Bed] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Beehive] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Brightness] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Building] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Camera] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Chat] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [CraftFromChest] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Deconstruct] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Durability] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [EitrRefinery] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Experience] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Fermenter] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [FireSource] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [FirstPerson] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Food] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [FreePlacementRotation] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Furnace] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Game] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [GameClock] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Gathering] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [GridAlignment] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Hotkeys] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Hud] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Inventory] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Items] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Kiln] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [LootDrop] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Map] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [MonsterProjectile] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Pickable] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Player] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [PlayerProjectile] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Server] Section is enabled.
[Info   :Valheim Plus] [Server] Updating serverSyncHotkeys from True to False
[Info   :Valheim Plus] [Server] Done with section.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Shields] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Smelter] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [SpinningWheel] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Stamina] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [StaminaUsage] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [StructuralIntegrity] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Tameable] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Time] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [ValheimPlus] Section is enabled.
[Info   :Valheim Plus] [ValheimPlus] Done with section.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Wagon] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Ward] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Windmill] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [WispSpawner] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Workbench] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] Downloading config from: 'https://raw.githubusercontent.com/grantapher/ValheimPlus/0.9.9.17/valheim_plus.cfg'
[Info   :Valheim Plus] Configuration file loaded succesfully.
[Info   :Valheim Plus] Applying patches.
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type ZNet and name RPC_ServerSyncedPlayerData and parameters
[Error  :Valheim Plus] Failed to apply patches.
[Warning:Valheim Plus] This version of Valheim Plus (0.9.9.17) expects a minimum game version of "0.217.11", but this game version is older at "0.216.9". Please either update the Valheim game, or use an older version of Valheim Plus as per https://github.com/Grantapher/ValheimPlus/blob/grantapher-development/COMPATIBILITY.md.
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static void ValheimPlus.GameClasses.PlayerPositionWatcher::Postfix(ZNet& __instance, ZRpc rpc)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
ValheimPlus.ValheimPlusPlugin.PatchAll () (at <aac7a9eeb26c4e3aad65fbd56513386a>:0)
ValheimPlus.ValheimPlusPlugin.Awake () (at <aac7a9eeb26c4e3aad65fbd56513386a>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.UI.Image:OnCanvasHierarchyChanged()

[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.1]
[Info   :   BepInEx] Loading [SeleniumMineBoom 1.0]
[Info   :   BepInEx] Loading [MassFarming 1.5]
[Info   :   BepInEx] Loading [XPortal 1.2.14]
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] 08/27/2023 10:26:32: Starting to load scene:start

[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Info   : Unity Log] 08/27/2023 10:26:33: Using environment steamid 892970

[Info   : Unity Log] 08/27/2023 10:26:33: Using steam APPID:892970

Setting breakpad minidump AppID = 892970
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198080553778 [API loaded no]
[Info   : Unity Log] 08/27/2023 10:26:33: Authentication:k_ESteamNetworkingAvailability_Attempting

[Info   : Unity Log] 08/27/2023 10:26:33: Steam initialized, persona:The Sylkie

[Info   : Unity Log] 08/27/2023 10:26:33: PlayFab custom ID set to "Steam_76561198080553778"

[Info   : Unity Log] 08/27/2023 10:26:33: Using default prefs

[Info   : Unity Log] 08/27/2023 10:26:33: Valheim version: 0.216.9 (network version 5)

[Info   : Unity Log] 08/27/2023 10:26:33: Worldgenerator version setup:2

[Info   :Jotunn.Managers.CommandManager] Adding 20 commands to the Console
[Info   : Unity Log] 08/27/2023 10:26:33: Render threading mode:MultiThreaded

[Info   :Jotunn.Managers.InputManager] Registering 7 custom inputs
[Warning: Unity Log] 08/27/2023 10:26:33: Missing audio clip in music respawn

[Info   : Unity Log] 08/27/2023 10:26:33: Checking for installed DLCs

[Info   : Unity Log] 08/27/2023 10:26:33: DLC:beta installed:False

[Info   : Unity Log] 08/27/2023 10:26:34: Loaded localization file #0 - 'localization' language: 'English'

[Info   : Unity Log] 08/27/2023 10:26:34: Loaded localization file #1 - 'localization_extra' language: 'English'

[Info   : Unity Log] 08/27/2023 10:26:34: Loaded localization file #0 - 'localization' language: 'English'

[Info   : Unity Log] 08/27/2023 10:26:34: Loaded localization file #1 - 'localization_extra' language: 'English'

[Info   :Valheim Plus] Version text: "Version 0.216.9 (n-5), ValheimPlus 0.9.9.17 (Grantapher Temporary)"
[Info   :Jotunn.Managers.KitbashManager] Applying Kitbash in 1 objects
[Info   :Jotunn.Managers.ItemManager] Adding 3 custom items to the ObjectDB
[Info   : Unity Log] 08/27/2023 10:26:34: Sending PlayFab login request (attempt 1)

[Info   : Unity Log] 08/27/2023 10:26:34: Session auth respons callback

[Info   : Unity Log] 08/27/2023 10:26:34: Ticket is System.Byte[] of length 369

[Info   : Unity Log] 08/27/2023 10:26:34: Starting music menu

[Info   : Unity Log] 08/27/2023 10:26:35: PlayFab logged in as "Steam_76561198080553778"

[Info   : Unity Log] 08/27/2023 10:26:35: PlayFab local entity ID is 90171CF6AB1EB38A

[Info   :Jotunn.Managers.InputManager] Registering 7 custom inputs
[Info   : Unity Log] 08/27/2023 10:26:49: Current res 3840x2160     3840x1937
**Version**
Which version of XPortal are you experiencing your problem with?
1-2-14

**Environment**
Choose from the following options where you are experiencing the problem (leave only the ones you know about):
* Singleplayer

**Other mods**
Do you experience the issue also when you do not have any other mods installed? If applicable, please provide the full list of mods that you are using.

**Priority**
Estimate how important this problem is. Choose Medium if you don't know.
* High (XPortal does not work at all anymore)

**Additional information**
Add any addtional information here. Anything that you think might help is appreciated.

**Comment by turotulco** [comment]
I also tried deactivating *all* other mods while loading the game. XPortal was the only one active. Same results.

**Comment by SpikeHimself** [comment]
Could you provide the logs of your attempt with only XPortal active?

Please attach the log as a file rather than pasting the contents in your message (you can just drag the file into the comment).

**Comment by turotulco** [comment]
I would love to. But as I stated, I couldn't figure out how to turn on debug logging. Is that an option in Thunderstore? The game itself? Or Steam?

**Comment by turotulco** [comment]
I found a player log, with only xPortal running, and a single error message. Hope this helps?
[Player.log](https://github.com/SpikeHimself/XPortal/files/12449559/Player.log)

**Comment by SpikeHimself** [comment]
> I would love to. But as I stated, I couldn't figure out how to turn on debug logging. Is that an option in Thunderstore? The game itself? Or Steam?

Sorry about that. I had an article that explained it in detail but I've removed the project that was sitting in. I'll make it visible again soon.



> I found a player log, with only xPortal running, and a single error message. Hope this helps? [Player.log](https://github.com/SpikeHimself/XPortal/files/12449559/Player.log)

I see an error in relation to a reference to gamepad input. I'll look into that.

**Comment by SpikeHimself** [comment]
I haven't spent time on this particular issue yet, but can you try again after updating XPortal to v1.2.15 and Jotunn to v2.12.7?

**Comment by turotulco** [comment]
No joy. The updates worked fine, but the reaction is the same. It seems like the cursor focus remains in the game world and never is transferred to the canvas with the widgets. When the configuration screen is open, there is no sword cursor, and any mouse movements remain locked to the look around function. Weird. But then, you could get that behavior without any error being logged, couldn't you? Yeah, still open. Sorry. :-p

**Comment by SpikeHimself** [comment]
I am unable to reproduce this. Going by the content of your latest logfile it seems you do indeed have the latest Jotunn and XPortal versions (at that time).

I do see a few errors regarding files Valheim couldn't load, and also your Valheim version is older (by a few days), but I don't think that those things could cause the error you're getting.

```
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/Mono/lib/usr/lib/libSystem.dylib
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/Mono/lib/usr/lib/libSystem.dylib.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/Mono/lib/usr/lib/libSystem.dylib
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/Mono/libc.so.6
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/Mono/libc.so.6.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/Mono/libc.so.6
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/Mono/data-0000028BEC0DE0C0.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/Mono/data-0000028BF0AB9040.dll
``` 

..and further down:

```
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/Mono/data-0000028C5767BCF0.dll
```

Just to make sure, could you verify your Valheim installation? You can do this in Steam by going to the properties window of the game, then under the tab "Installed Files" there should be a "Verify integrity of game files" button:

![image](https://github.com/SpikeHimself/XPortal/assets/123466188/ff45386b-4ae2-46d8-9f83-9818e02a9d6a)

**Comment by turotulco** [comment]
All 159 files successfully validated. Those Valheim version dates look weird. Mine is in American date format and yours is in Euro date format. That shouldn't make a difference though, we should both still have the same files, right? I checked my update options, and it was set to only update when I launch it, so I changed that back to always update this game.  I'll see if I can figure out how to make an mp4 of the gameplay so it makes a little more sense to you. Can you recommend any good capture utilities for that?

**Comment by turotulco** [comment]
Hmmmm... those files that cannot be loaded are all Mono files. I have several versions of Unity installed, and Visual Studio 2019 and 2022. I'm thinking there might be a conflict there? Though I don't know how, Steam keeps it's data files pretty compartmentalized.

**Comment by SpikeHimself** [comment]
Hi @turotulco - you're right, it seems weird, and I don't think having Unity installed on your machine should affect this.

In issue #66 people with the same error seem to have resolved it by updating their game. Can you reinstall perhaps? Maybe something got corrupted along the way. The nature of the error suggests that XPortal is calling a function that Valheim does not have, which can only point to a discrepancy in version, and your logs support that.

**Comment by SpikeHimself** [comment]
Hi @turotulco, I haven't heard back from you so I'm going to assume it was fixed (it was confirmed fixed by others, after all). If you are still experiencing problems, please feel free to re-open or create a new issue.
