### ISSUE TITLE
Buttons "OK" not  visible and cannot close portal configuration window

### ISSUE THREAD

**Issue by DannyW5** [SpikeHimself/XPortal#66]
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/12503892/LogOutput.log)

Buttons "OK" not  visible and cannot close portal configuration window. I can only interact with window (change the name of portal, switching between inputs ) when map is opened

Expected behaviour is to have possibility to close portal configuration window and interact with window in normal way.

**LogOutput file(s)**
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/12503892/LogOutput.log)

**Version**
1.2.15

**Environment**
Choose from the following options where you are experiencing the problem (leave only the ones you know about):
* Singleplayer

**Other mods**
Do you experience the issue also when you do not have any other mods installed? If applicable, please provide the full list of mods that you are using.
I have 2.12.7 Jotunn mod version installed. It doesn't break functionality of other mods.

**Priority**
* High (XPortal does not work at all anymore)

**Additional information**
I've downloaded version 1.2.10 of XPortal and window works properly then but travelling by portals not.

**Comment by SpikeHimself** [comment]
Hi @DannyW5, thank you for reporting this issue. Could you provide a screenshot of what it looks like?

**Comment by DannyW5** [comment]
Yes, here youe have it...
![image_bug](https://github.com/SpikeHimself/XPortal/assets/109547198/d57bd796-6cd9-47e3-8127-b83851722889)

**Comment by SpikeHimself** [comment]
Very curious!

You only have Jotunn and XPortal installed? No other mods at all?

Could you enable Debug logging in the BepInEx config file, and then send me your output log file?

**Comment by DannyW5** [comment]
List of mods installed:
- Epic Loot
- Odin Architect
- Unrestricted Portals
- Clock mode 
- Equipment and Quick Slots
- Farm Grid
- Mass Farming
- Skills give more carry weight
- Trash items
- Recycle

**Comment by SpikeHimself** [comment]
Never mind my previous comment. You already provided the log file, I didn't see it, apologies.

When you interact with a portal, you are getting this error in the console:

```
XPortal.UI.PortalConfigurationPanel.InitialiseUI () (at <4ba998a79d4348cf9f45bb0b517b89c6>:0)
XPortal.UI.PortalConfigurationPanel.ConfigurePortal (XPortal.KnownPortal portal) (at <4ba998a79d4348cf9f45bb0b517b89c6>:0)
XPortal.XPortal.OnPortalRequestText (ZDOID portalId) (at <4ba998a79d4348cf9f45bb0b517b89c6>:0)
XPortal.Patches.TextInput_RequestText.Prefix (TextReceiver sign) (at <4ba998a79d4348cf9f45bb0b517b89c6>:0)
(wrapper dynamic-method) TextInput.DMD<TextInput::RequestText>(TextInput,TextReceiver,string,int)
TeleportWorld.Interact (Humanoid human, System.Boolean hold, System.Boolean alt) (at <626237b373794d99b107dbbe70f148d2>:0)
(wrapper dynamic-method) Player.DMD<Player::Interact>(Player,UnityEngine.GameObject,bool,bool)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)
```

Which is the same issue reported in #65 

Could you verify your Valheim installation? You can do this in Steam by going to the properties window of the game, then under the tab "Installed Files" there should be a "Verify integrity of game files" button:

![image](https://github.com/SpikeHimself/XPortal/assets/123466188/ff45386b-4ae2-46d8-9f83-9818e02a9d6a)

**Comment by DannyW5** [comment]
I managed to fix problem with window, but this mod still doesn't work for me. I got right now such exception in Log.
[Warning:Jotunn.EventExtensions] Exception thrown at event InvokeOnVanillaMapDataLoaded in XPortal.MinimapManager_OnVanillaMapDataLoaded:
System.MissingMethodException: long ZDOMan.GetMyID()
  at Jotunn.EventExtensions.SafeInvoke (System.Action events) [0x00018] in <2313992615e843afabf13f266680a96f>:0

**Comment by SpikeHimself** [comment]
Could you enable Debug logging in the BepInEx config file, and then send me your output log file?

**Comment by DannyW5** [comment]
@SpikeHimself 
I have Valheim version 0.216.8 so i downloaded Jotunn version 2.11.7 and Xportal version 1.2.10

**Comment by DannyW5** [comment]
Could you tell me how to enable debug logging in BepInEx?

**Comment by SpikeHimself** [comment]
> @SpikeHimself I have Valheim version 0.216.8 so i downloaded Jotunn version 2.11.7 and Xportal version 1.2.10

Sorry but I can't help with those. Those old versions are deprecated and I can't offer support.

> Could you tell me how to enable debug logging in BepInEx?

https://github.com/SpikeHimself/resources/wiki/BepInEx:-Enable-debug-logging

**Comment by LordDelacroix** [comment]
I have this problem as well. 
1. BepinEx v5.4.21.0
2. Jotunn 2.12.4
3. Valheim 217.14 (n-12)
4. XPortal 1.2.15

No other mods are installed at this time, The interface is missing all other buttons, and the mouse is no longer visible while the dialog is up. Pressing TAB or SHIFT-TAB does not move focus to the dropdown or any other control. Pressing ESC does close the dialog as does ENTER. I am able to rename the portal upon which I pressed the E key by pressing ENTER.

**Comment by DannyW5** [comment]
@LordDelacroix Try to update Jotunn to 2.12.7

@SpikeHimself I managed to solve my issue, updating Valheim, Jotunn and XPortal  to newest version

**Comment by LordDelacroix** [comment]
Yup - just found the new version on NexusMods and it has solved my problem as well!  WOOT!

**Comment by LordDelacroix** [comment]
Do you have a patreon page?

**Comment by SpikeHimself** [comment]
Thanks for the feedback both!



> Do you have a patreon page?

No, I don't. I did use a donation service previously but they have deactivated my account for strange reasons they weren't able to explain to me. Maybe I'll set up something new later. Thanks for your support either way!
