### ISSUE TITLE
Compatibility with Project Auga

### ISSUE THREAD

**Issue by VamPerL** [SpikeHimself/XPortal#69]
Everything works, yet I cannot give portals a name that is longer than a single digit, since the textbox is deselecting so quickly after selecting it. 
I could imagine it being related to Project Auga, do you have any experiences with that?
Unfortunately, I don't get any error message that I could give you. 
Regardless of this issue, I would love it, if your mod would be implemented/compatible with Project Auga :)

**Comment by SpikeHimself** [comment]
Hi @VamPerL, thank you for reporting this.

Could you provide your logfile and could you share a screenshot of what the portal configuration window looks like?

**Comment by VamPerL** [comment]
Of course, here it is:
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/12583816/LogOutput.log)
![Untitled](https://github.com/SpikeHimself/XPortal/assets/80795460/47a93d2a-735d-4f75-845e-f147a2242d1c)

**Comment by SpikeHimself** [comment]
Hi @VamPerL could you enable debug logging and send me a new logfile?

https://github.com/SpikeHimself/resources/wiki/BepInEx:-Enable-debug-logging

**Comment by VamPerL** [comment]
There you go:
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/12584070/LogOutput.log)

**Comment by VamPerL** [comment]
Okay, here another try:
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/12585478/LogOutput.log)

**Comment by VamPerL** [comment]
I just realized, that it is also happening in the console after opening it with F5. Whenever I select the text field the bar blinks once and then deselects. Might also be caused by another mod. Thank you for reaching out to the Author of Auga for this :)

**Comment by VamPerL** [comment]
I confirm it's Auga, both effects.

**Comment by SpikeHimself** [comment]
> I just realized, that it is also happening in the console after opening it with F5. Whenever I select the text field the bar blinks once and then deselects.

Okay, this makes it quite clear that it's not related to XPortal. I will close the issue, but if anything new comes up, do feel free to comment here and/or re-open the issue.

It probably helps the author of Auga to know that you also experience the issue with the console focus, so you might want to inform them about it here: https://github.com/RandyKnapp/Auga/issues/205

**Comment by VamPerL** [comment]
Yes, I had seen it, thank you so much for your efforts :)
