### ISSUE TITLE
As of 217.28 Xportal stopped working for me.

### ISSUE THREAD

**Issue by Jeffglobalmotion** [SpikeHimself/XPortal#79]
**Describe the bug**
I try to label the portal, and I can't.  I can't choose a destination because it is unresponsive altogether.

**To Reproduce**
Step up to portal, press E, nothing happens.

**Expected behaviour**
Menu screen for label of portal and label of destination.

**LogOutput file(s)**
I just removed the plugin and it worked as vanilla so I don't have the log file that I think would help you... idk  I text searched for XPortal and it's not listed in the Log file... my bad.

**Version**
Update to v1.2.18. from nexusmods

**Environment**
Choose from the following options where you are experiencing the problem (leave only the ones you know about):

* Singleplayer

**Other mods**
PlantEverything, AzuMapDetails, AzuWorkbenchInventoryRepair, BetterLaddersContinued, ClockMod, ExtendedPlayerInventory, Floaty, InstantMonsterDrop, MassFarming, MultiCraft, NoFoodDegradation, OdinsFoodBarrels, QuickStackStore, TimeMod, UseEquipmentInWater, Valheim.DisplayBepInExInfo (default dll)

**Priority**
* High (XPortal does not work at all anymore)

**Additional information**

Thank you for your time and consideration!

**Comment by SpikeHimself** [comment]
Hi @Jeffglobalmotion, thank you for reporting! 

> I just removed the plugin and it worked as vanilla so I don't have the log file that I think would help you... idk I text searched for XPortal and it's not listed in the Log file... my bad.

I'm afraid that without a log file I cannot find what the issue could be, since I am not experiencing this issue myself.

Can you install XPortal again, enable debug logging, and try again, to create a new logfile?

https://github.com/SpikeHimself/resources/wiki/BepInEx:-Enable-debug-logging

**Comment by lordniah** [comment]
I'm also experiencing the same issue on both dedicated and local with all other mods disabled.  Log file is copied below:


[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/13283688/LogOutput.log)

**Comment by SpikeHimself** [comment]
> since I am not experiencing this issue myself

I hadn't seen the new game update yet when I wrote this.

Version 1.2.19 has just been released and the issue should be fixed.
