### ISSUE TITLE
Xportal Unable to interact with portal

### ISSUE THREAD

**Issue by NOTurDodge** [SpikeHimself/XPortal#81]
**Describe the bug**
I have the latest version of jotunn and your mod installed along with bepinx Installed but while Ingame when interacting with the portal the GUI for Xportal doesnt show.

**To Reproduce**
The only mod I have other than this which might be causing the issue(Unlikely) is 'Teleport Everything'

**LogOutput file(s)**
[Error  :XPortal.Log] PixelFix GUI not found
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
XPortal.UI.PortalConfigurationPanel.ConfigurePortal (XPortal.KnownPortal portal) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:
0)
XPortal.XPortal.OnPortalRequestText (ZDOID portalId) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.Patches.TextInput_RequestText.Prefix (TextReceiver sign) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
(wrapper dynamic-method) TextInput.DMD<TextInput::RequestText>(TextInput,TextReceiver,string,int)
TeleportWorld.Interact (Humanoid human, System.Boolean hold, System.Boolean alt) (at <37016fb1154444bda541f76782d9fa64>:0)
Player.Interact (UnityEngine.GameObject go, System.Boolean hold, System.Boolean alt) (at <37016fb1154444bda541f76782d9fa64>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

**Version**
1.2.19

**Environment**
* Singleplayer

**Other mods**
Other than teleport everything I have ;
1.BuildIt
2.Odin Architect
3.Cave Sounds Be Gone
4.Magcial Weapons
5.Plant Everything
6.Farm Grid
7.AllTheBases

I have tried to run Xportal with all of these disabled to no avail 

**Priority**

* High (XPortal does not work at all anymore)

Any Help will be much appreciated ,Thanks in Advance!

**Comment by SpikeHimself** [comment]
Hi @NOTurDodge, thank you for reporting. Can you double check that you have the latest version of Valheim? There was an update recently that renamed a UI element that XPortal relies on, and I released a new version of XPortal to address that, but the error you are seeing comes from the check in that new version, indicating that you have an older version of Valheim (unless there's been another update and they have changed that element again, of course, but I don't see any update notes right now).

**Comment by SpikeHimself** [comment]
Hi @NOTurDodge, I heard nothing from you so I am going to assume the issue resolved itself. Let me know if that's not the case.

**Comment by huntzilla360c** [comment]
![Screenshot (1)](https://github.com/SpikeHimself/XPortal/assets/61102631/cc9fd785-74c4-4c0d-ad6e-668736bd970e)

![20240426173625_1](https://github.com/SpikeHimself/XPortal/assets/61102631/571f9de3-ee2e-4695-92bb-6e7eba838953)

![20240426173632_1](https://github.com/SpikeHimself/XPortal/assets/61102631/7151a914-fa7f-431f-8200-643c456ce1fd)

I'm having this issue, I've updated every single mod I could, there are no conflicts with any other mod but I'm seeing GUI issues with Jotun in the console. Jotun is installed but i dont think correctly, as i had all the jotun files just sitting in my plugins folder on my old PC where Xportal WAS working, but i looked on the ThunderStore and it says to just drop the Xportal and the Jotun folders into the Plugins folder

**Comment by huntzilla360c** [comment]
![Screenshot 2024-04-26 174725](https://github.com/SpikeHimself/XPortal/assets/61102631/bfbf0282-3625-46e3-86f4-9bc7ef55c28c)
