### ISSUE TITLE
Latest Jotunn update broke XPortal: Dialog Window not working anymore

### ISSUE THREAD

**Issue by SolSeptem** [SpikeHimself/XPortal#83]
**Describe the bug**
When interacting with the portal, the window is not dismissable, and fields cant be interacted with. this blocks the game from being played because the window stays in your face. This ocurred only after updating to Jotunn 2.15.1

BepInEx log is as follows:

[Error  : Unity Log] MissingFieldException: Field not found: System.Collections.Generic.Dictionary`2<TMPro.TextMeshProUGUI, string> .Localization.textMeshStrings Due to: Could not find field in class
Stack trace:
XPortal.UI.PortalConfigurationPanel.AddGamepadHint (UnityEngine.GameObject go, System.String buttonName, UnityEngine.KeyCode keyCode) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.UI.PortalConfigurationPanel.InitialiseUI () (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.UI.PortalConfigurationPanel.ConfigurePortal (XPortal.KnownPortal portal) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.XPortal.OnPortalRequestText (ZDOID portalId) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.Patches.TextInput_RequestText.Prefix (TextReceiver sign) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
(wrapper dynamic-method) TextInput.DMD<TextInput::RequestText>(TextInput,TextReceiver,string,int)
TeleportWorld.Interact (Humanoid human, System.Boolean hold, System.Boolean alt) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
(wrapper dynamic-method) Player.DMD<Player::Interact>(Player,UnityEngine.GameObject,bool,bool)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

**To Reproduce**
Update Jotunn to the latest version and try to interact with a portal. 

**Expected behaviour**
Expected is that the window works as before the update to jotunn 2.15.1

**LogOutput file(s)**
see above

**Version**
1.2.19

**Environment**
Singleplayer

**Other mods**

many but none involving portals. Things I can think of that might interact are 

AzuExtendedPlayerInventory
SearsCatalog
All Warfare mods by Therzie

**Priority**

* Critical * interacting with a portal breaks your game

**Additional information**

**Comment by waylonflinn** [comment]
Confirmed. Same issue for me.

**Comment by SolSeptem** [comment]
the Jotunn 2.15.2 update did not change anything it seems

**Comment by Tripnip** [comment]
My portals are also broken.
only update i had was for BepInExPack_Valheim by denikson 
but we both share the 
AzuExtendedPlayerInventory Mod so just putting that out there

**Comment by Vikingtons** [comment]
Wasn't this caused by the Valheim 0.217.38 patch?

**Comment by SpikeHimself** [comment]
Thanks for reporting everyone. v1.2.20 should have fixed this issue, let me know if you run into any problems.
