### ISSUE TITLE
Portal menu stuck

### ISSUE THREAD

**Issue by Dynamofire8** [SpikeHimself/XPortal#84]
**Describe the bug**
When clicking on a portal to change its destination the pop up menu which appears does not let you click on it. The mouse disappears and one cannot select a new location from the drop down. You also cannot get rid of the menu.

**To Reproduce**
When clicking on a portal to change its destination the pop up menu which appears does not let you click on it. The mouse disappears and one cannot select a new location from the drop down. You also cannot get rid of the menu.

**Expected behaviour**
You should be able to click on the drop down menu and pick a new portal location

**LogOutput file(s)**
Please have `Debug` output enabled. Attach the file called `LogOutput.log` which can be found in the directory `Valheim\BepInEx\`.
If you play on a server, include the server's `LogOutput.log` as well.

**Version**
1.2.19

**Environment**
* Singleplayer

**Other mods**
Do you experience the issue also when you do not have any other mods installed? If applicable, please provide the full list of mods that you are using.

Yes it is still broken

**Priority**
* Critical (my world is suffering permanent damage from XPortal)

**Additional information**
Add any addtional information here. Anything that you think might help is appreciated.

**Comment by Liora42** [comment]
I am experiencing the same issue, which started today after updating the game and Jotunn.

**Comment by adultbug** [comment]
Bump. Same here!

**Comment by FGCflukey** [comment]
Same here!

**Comment by Tripnip** [comment]
Same thing here. 
BepInExPack_Valheim by denikson
that was my only mod that updated before portals broke.

**Comment by FGCflukey** [comment]
```
[Error  : Unity Log] MissingFieldException: Field not found: System.Collections.Generic.Dictionary`2<TMPro.TextMeshProUGUI, string> .Localization.textMeshStrings Due to: Could not find field in class
Stack trace:
XPortal.UI.PortalConfigurationPanel.AddGamepadHint (UnityEngine.GameObject go, System.String buttonName, UnityEngine.KeyCode keyCode) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.UI.PortalConfigurationPanel.InitialiseUI () (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.UI.PortalConfigurationPanel.ConfigurePortal (XPortal.KnownPortal portal) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.XPortal.OnPortalRequestText (ZDOID portalId) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.Patches.TextInput_RequestText.Prefix (TextReceiver sign) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
(wrapper dynamic-method) TextInput.DMD<TextInput::RequestText>(TextInput,TextReceiver,string,int)
TeleportWorld.Interact (Humanoid human, System.Boolean hold, System.Boolean alt) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
Player.Interact (UnityEngine.GameObject go, System.Boolean hold, System.Boolean alt) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
XPortal.UI.PortalConfigurationPanel.ConfigurePortal (XPortal.KnownPortal portal) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.XPortal.OnPortalRequestText (ZDOID portalId) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.Patches.TextInput_RequestText.Prefix (TextReceiver sign) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
(wrapper dynamic-method) TextInput.DMD<TextInput::RequestText>(TextInput,TextReceiver,string,int)
TeleportWorld.Interact (Humanoid human, System.Boolean hold, System.Boolean alt) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
Player.Interact (UnityEngine.GameObject go, System.Boolean hold, System.Boolean alt) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
XPortal.UI.PortalConfigurationPanel.ConfigurePortal (XPortal.KnownPortal portal) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.XPortal.OnPortalRequestText (ZDOID portalId) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.Patches.TextInput_RequestText.Prefix (TextReceiver sign) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
(wrapper dynamic-method) TextInput.DMD<TextInput::RequestText>(TextInput,TextReceiver,string,int)
TeleportWorld.Interact (Humanoid human, System.Boolean hold, System.Boolean alt) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
Player.Interact (UnityEngine.GameObject go, System.Boolean hold, System.Boolean alt) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)
```

**Comment by FGCflukey** [comment]
> Same thing here. BepInExPack_Valheim by denikson that was my only mod that updated before portals broke.

[Jotunn the Valheim Library] which is required by this mod, was updated. Likely Xportal needs to lineup with Jotunn update.

Sadly this stops me from playing as my portals are broken.

**Comment by AlinaPanda** [comment]
I have the same problem after the update :((

**Comment by FGCflukey** [comment]
Scrapped this mod. Using Better Portals because it works and doesn't rely on Jotun library.. least I can play again...

**Comment by SpikeHimself** [comment]
Thanks for reporting everyone. v1.2.20 should have fixed this issue, let me know if you run into any problems.

**Comment by SpikeHimself** [comment]
> Scrapped this mod. Using Better Portals because it works and doesn't rely on Jotun library.. least I can play again...

Sorry to hear that you feel this way @FGCflukey. Sadly this is how modding works. You are using software modifications which lack official support. Things can break at any moment. Luckily I was able to fix this in my free time within a respectable timeframe. Good luck out there!
