### ISSUE TITLE
XPORTAL BUG

### ISSUE THREAD

**Issue by BiiielsouzaXD** [SpikeHimself/XPortal#87]
Well, since the last update of xportal I came across the following bug

![adsadsa](https://github.com/SpikeHimself/XPortal/assets/153947977/cef0e818-7343-4190-84cf-e3d0db92942b)

what to do?

**Comment by SpikeHimself** [comment]
Hi @BiiielsouzaXD, when you create a new issue, there's a template with questions to fill in. I need the answers to those questions in order to properly assess your issue. That's in fact the very reason I created that template. Can you please fill in the template? Thank you.

**Comment by vasilyvaganov** [comment]
@BiiielsouzaXD update the xportal and jotunn mod (dependency), after that everything works fine
