### ISSUE TITLE
Error on game load, cannot launch a save. 

### ISSUE THREAD

**Issue by TheVillain-Inc** [SpikeHimself/XPortal#88]
**Describe the bug**
Upon loading the game up, seeing a wall of red errors on the log, game quickly becomes unresponsive. 

**To Reproduce**
Currently running xportals for the first time on a midweight modpack of 32 mods. 

**Expected behaviour**
Describe what you expected to happen (if it's not obvious).

**LogOutput file(s)**
Please have `Debug` output enabled. Attach the file called `LogOutput.log` which can be found in the directory `Valheim\BepInEx\`.
If you play on a server, include the server's `LogOutput.log` as well.

**Version**
1.2.20

**Environment**
Choose from the following options where you are experiencing the problem (leave only the ones you know about):
* Singleplayer

**Other mods**
Do you experience the issue also when you do not have any other mods installed? If applicable, please provide the full list of mods that you are using.

Ok so I'd normally try running with only xportals but I just came back to Valheim and got my mod list working. So im reluctant to risk wiping it right. I'll try a clean load when I find the courage. 

**Priority**
Estimate how important this problem is. Choose Medium if you don't know.
* High (XPortal does not work at all anymore)

**Additional information**
Add any addtional information here. Anything that you think might help is appreciated.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) ZInput.DMD<ZInput::GetButtonDown>(string)
UIGamePad.ButtonPressed () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
UIGamePad.Update () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

This is appearing in the Bepinex Log over and over. 

![image](https://github.com/SpikeHimself/XPortal/assets/25729205/bdff3e09-c8fa-4056-99ba-e01d4748a164)

**Comment by TheVillain-Inc** [comment]
Acquired log. 

[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/13705059/LogOutput.log)

**Comment by SpikeHimself** [comment]
Hi @TheVillain-Inc - what about this makes you believe it's an issue related to XPortal?

I see no XPortal related errors in your log file.

Since you said you've just come back from a break, can you try updating everything else as well? That is, the game, BepInEx, Jotunn, etc..?

**Comment by TheVillain-Inc** [comment]
Caaan do - though disabling/enabling Xportals causes the above. Might be a conflict - but the only file Vortex is listing as conflicting is the Changelog. 

Normally I'd use Mod Organiser2 so its also possible this is user error from that point. 

So far my other mods are running happily up to date, lastest game version on Steam, will check my BepInEx install as I trusted Vortex to do that.

**Comment by SpikeHimself** [comment]
Your Jotunn is out of date by 2 versions. This version of XPortal was made for Jotunn 2.15.2, and you are running Jotunn 2.15.0.

**Comment by TheVillain-Inc** [comment]
Weeeell shit. I guess I cant trust Vortex to actually alert me for mod updates. Which you'd really think is part of its main function. 

Having updated Jotunn Xportal isn't throwing a massive wobble. Have just started playing again so making a portal might take a bit. But this core mod update _might_ have been the problem. 

My apologies, I know how frustrating it is to go through a bug report and the answer is 'please update your core mods'.

**Comment by SpikeHimself** [comment]
All good, glad you got it sorted!
