### ISSUE TITLE
Fetching Portals Info

### ISSUE THREAD

**Issue by Postyon** [SpikeHimself/XPortal#9]
new portals says "Fetching portals Info" and can't be destroyed

**Comment by SpikeHimself** [comment]
Thanks for reporting!

Are you playing single player or do you join a server? Is the server also running the latest version?

Could you turn on debug logging and send me your BepInEx output logs? If you run a server seperately, then please also provide the logs of the server.

See also #10

**Comment by SpikeHimself** [comment]
Closing as duplicate of #10
