### ISSUE TITLE
Menus Broken - Method not found: ZInput/ButtonDef errors

### ISSUE THREAD

**Issue by jms005** [SpikeHimself/XPortal#90]
**Describe the bug**
When Valheim starts, the main game menu is broken - all menu strings are broken, for example displaying "$menu_back", "$menu_selectworld", etc.  Select World menu starts open, before selecting Start Game.

This issue has come up repeatedly with Jotunn 1.15.0, where the fix is to use 1.15.2.  Opening issue since the problem is occurring here for me.

**To Reproduce**
This occurs when launching game with R2Modman on Valheim 0.217.31 with only XPortal 1.2.20, Jotunn 1.15.2 and BepInEx 5.4.2202.

**LogOutput file(s)**
Log output appended to issue.

**Version**
XPortal 1.2.20

**Environment**
Running Valheim 0.217.31 on Windows 10, Steam, single player, local game.

**Other mods**
Only Jotunn, XPortal & BepInEx

**Priority**
High 

**Additional information**
![20231228091413_1](https://github.com/SpikeHimself/XPortal/assets/29104325/2a5b42fa-6b94-414a-a02d-9bcbdbb7e79a)

[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/13788449/LogOutput.log)

**Comment by SpikeHimself** [comment]
Strange issue! The error is coming from Jotunn (not XPortal), it's trying to use functionality from the game that does not appear to exist. I've seen this before where the fix was to update to 2.15.2, just like you said, but clearly you have done that (your logs confirm it).

Have you tried verifying the game files via Steam? And removing/reinstalling Jotunn?

**Comment by SpikeHimself** [comment]
Just noticed your screenshot says "BETA" in the corner, are you running the test version of Valheim?

**Comment by jms005** [comment]
Yes, that was the problem, I had forgotten that I had been on old stable.  Sorry for the issue, thanks for the attention - and for that awesome mod, cannot play without at this point.
