### ISSUE TITLE
mod doesn't work

### ISSUE THREAD

**Issue by njikm2010** [SpikeHimself/XPortal#91]
**Describe the bug**
Hello, this mod doesn't work properly on my computer.
It is as if he has not installed this mod, and the portal is exactly the same as the original one.

BepLnEx Shell Out.txt is the log in the console when I open the game.

**To Reproduce**

**Expected behaviour**
The mod works fine

**LogOutput file(s)**
[BepLnEx Shell Out.txt](https://github.com/SpikeHimself/XPortal/files/13965933/BepLnEx.Shell.Out.txt)
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/13965935/LogOutput.log)

**Version**

xPortal :  1.20.0
Jotunn library : 2.16.1

**Environment**
Choose from the following options where you are experiencing the problem (leave only the ones you know about):
* Singleplayer

**Other mods**
No, I turned off all other mods to test

**Priority**
Estimate how important this problem is. Choose Medium if you don't know.
* High (XPortal does not work at all anymore)

**Additional information**
![image](https://github.com/SpikeHimself/XPortal/assets/13850486/d78a1bc7-9959-415f-abeb-4915ce6bb2b0)

**Comment by SpikeHimself** [comment]
Hi, according to your log file you are running a **very** old version of BepInEx: v5.4.9.0. 

Can you update this and see if the problem persists? The current version at the time of writing is 5.4.22

**Comment by SpikeHimself** [comment]
> [LogOutput.log](https://github.com/SpikeHimself/XPortal/files/14087744/LogOutput.log) yep. I also found this problem and updated it.Still not working properly.

This log file seems to cut off early and doesn't show anything beyond loading the game (no gameplay). I can't see any errors  in it.

What could also help is turning on [BepInEx Debug logging](https://github.com/SpikeHimself/resources/wiki/BepInEx:-Enable-debug-logging)

**Comment by njikm2010** [comment]
sorry. My BepInEx configuration does enable debug, but for some reason there is no corresponding information in the log file. This is the output of the console. Can you take a look?
[BepLnEx Shell Out.txt](https://github.com/SpikeHimself/XPortal/files/14100063/BepLnEx.Shell.Out.txt)

**Comment by SpikeHimself** [comment]
Also please make sure that you are running the live version of the game, not a beta or an older version;

![image](https://github.com/SpikeHimself/XPortal/assets/123466188/83aff6fa-8375-4be3-b2f6-a916ecf38283)

**Comment by njikm2010** [comment]
It's really very strange. My version is indeed the latest live version and has been checked for integrity, but it does not work properly when I use **Vortex** as my Mod Manager. Later, when I used **ThunderStore** as my Mod management software, it worked normally. It's really, really incredible! ! But anyway, thanks for your help.

**Comment by SpikeHimself** [comment]
That's very weird, and not something I've seen before. I use Vortex myself and don't have this issue.

If you ever work out what the root cause was I'm very curious to learn about it :)

**Comment by njikm2010** [comment]
As you said, I don't know why it was initialized prematurely. When I use `ThunderStore`, it is only initialized when I enter the world. I'm also curious about the specific reasons. And please let me know if this mod can work on Linux server. I followed the instructions in the documentation to move to the server but it was prompted that the mod version was inconsistent.
