### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by 1747672002** [SpikeHimself/XPortal#92]
**Question 1: What is the name of the language you are translating to?**

Please use the English name as it is used on this page:  https://valheim-modding.github.io/Jotunn/data/localization/language-list.html

Chinese

**Question 2: Please replace the English translations in quotation marks below:**

1: Portal description: "连接到另一个传送门",
2: Set tag: "配置",
3: Tag: "名称",
4: Target: "目的地",
5: Target 'none': "(无)",
6: Name 'no name': "(无名称)",
7: XPortal UI header title: "道路千万条，安全第一条！"
8: Connects to another portal: "连接到另一个传送门"

**Comment by SpikeHimself** [comment]
Thank you, I will include this in the next release!

**Comment by SpikeHimself** [comment]
Your translation was added, the new version that includes it should be released somewhere this week, thanks again!
