### ISSUE TITLE
Error  :XPortal.Log] Portal `1894503392:1562065` is being destroyed, but XPortal does not know it

### ISSUE THREAD

**Issue by Jester2020** [SpikeHimself/XPortal#94]
**Describe the bug**
Generarlly errors when a created portal is destroyed. When this happens occasionally an error loop happens slowing the game to unplayability.

**To Reproduce**
Create a portal and destory it. Sometimes i think it might happen just going through a portal even though it wasn't destroyed.

**Expected behaviour**
Should not error xPortal should know that a portal is destroyed and an error loops should not happen in theory causing the error loop and eventually slowdown of the game until it's unplayable

**LogOutput file(s)**
I don't have Debug enabled and I dont see the option in the Xportal.cfg. will gladly turn it on with some instruction and update the log file when it happens again.

**Version**
XPortal v1.2.20 by SpikeHimself

**Environment**
Choose from the following options where you are experiencing the problem (leave only the ones you know about):
* Singleplayer

**Other mods**
I have not tested it without any other mods installled. Currently running a farely large list that could be causing conflicts
denikson-BepInExPack_Valheim-5.4.2202
RandyKnapp-EpicLoot-0.9.37
ValheimModding-Jotunn-2.16.2
Nextek-SpeedyPaths-1.0.8
RustyMods-Seasonality-3.1.9
Advize-PlantEasily-1.7.2
BentoG-MissingPieces-2.0.6
Tequila-Dvergr_Pieces-2.6.1
Frogger-InfiniteTorches-0.0.2
hyr-ItemStacks-1.2.0
Azumatt-AzuExtendedPlayerInventory-1.3.10
Azumatt-AzuMiscPatches-1.2.0
Azumatt-AzuSigns-1.0.5
Azumatt-AzuSkillTweaks-1.0.3
Azumatt-AzuWorkbenchTweaks-1.0.2
Trinsic-Better_Wisplight-1.0.0
blacks7ar-BowPlugin-1.7.3
blacks7ar-CombatOverhaulREwrite-1.1.8
Smoothbrain-CreatureLevelAndLootControl-4.5.19
CSG-CSG_Warfare_Monstrum_Epic_Loot_Support-1.0.3
Azumatt-DeathPinRemoval-1.0.4
MSchmoecker-FenceSnap-0.3.0
Smoothbrain-GapFiller-1.0.4
coemt-GimmeFuelGimmeFire-0.0.5
ComfyMods-Gizmo-1.9.0
blacks7ar-Herbalist-1.3.2
Azumatt-ImFRIENDLY_DAMMIT-1.1.2
shudnal-JustSleep-1.0.2
Goldenrevolver-Loyal_Spears_Auto_Pickup_And_Return_To_Owner-1.0.1
blacks7ar-MagicPlugin-1.8.5
Therzie-Warfare-1.6.5
Therzie-Monstrum-1.3.4
MSchmoecker-MultiUserChest-0.5.6
Smoothbrain-PassivePowers-1.0.12
MSchmoecker-PressurePlate-0.9.2
JereKuusela-Projectile_Collision-1.6.0
shudnal-ProtectiveWards-1.1.10
Azumatt-ResourceUnloadOptimizer-1.0.2
Vapok-ShieldMeBruh-1.0.8
AedenthornModding-ShowContainerContents-0.4.0
JereKuusela-Smoke_Collision-1.8.0
Goldenrevolver-Sorted_Menus_Cooking_Crafting_and_Skills_Menu-1.3.3
MSchmoecker-VNEI-0.14.1
SpikeHimself-XPortal-1.2.20
BetterUI_ForeverMaintained-BetterUI_ForeverMaintained-2.5.4
JereKuusela-Server_Sync_Fix-1.3.0
Therzie-Armory-1.1.7
Smoothbrain-Foraging-1.0.8
Korppis-Spearfishing-1.0.2
Smoothbrain-DualWield-1.0.9
Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock-1.4.5
Smoothbrain-StartupAccelerator-1.0.2
Advize-PlantEverything-1.16.2
Smoothbrain-Farming-2.1.12
Marlthon-OdinShipPlus-0.4.6
Smoothbrain-Exploration-1.0.2
Smoothbrain-Sailing-1.1.7
Smoothbrain-Evasion-1.0.3
Smoothbrain-Lumberjacking-1.0.5
Smoothbrain-Ranching-1.1.3
Smoothbrain-Mining-1.1.5
Smoothbrain-Blacksmithing-1.2.5
Smoothbrain-Tenacity-1.0.3
Smoothbrain-PackHorse-1.0.3
Smoothbrain-ComfortTweaks-3.2.10
Smoothbrain-FoodCustomizer-1.0.4
Smoothbrain-ShutUp-1.0.2
Azumatt-Recycle_N_Reclaim-1.3.1
Smoothbrain-Cooking-1.1.15
HappyDragoon-DragoonCapes-1.2.81
JereKuusela-Server_devcommands-1.74.0
Azumatt-PerformanceTracker-1.0.3
Smoothbrain-SmoothSave-1.0.5
GemHunter1-NoAFKEvents-1.0.2
VentureValheim-Venture_Location_Reset-0.7.0
JereKuusela-Upgrade_World-1.47.0
Azumatt-AzuAutoStore-2.1.4
aedenthorn_mods-CraftFromContainers-3.5.0
Digitalroot-Digitalroots_Slope_Combat_Assistance-2.0.22
blacks7ar-LootParticlePlus-1.1.0
Azumatt-Official_BepInEx_ConfigurationManager-18.2.0
Therzie-WarfareFireAndIce-1.1.4
Therzie-MonstrumAshlands-1.1.5
Therzie-MonstrumDeepNorth-1.1.6
Digitalroot-Bounties-3.0.9

**Priority**
Estimate how important this problem is. Choose Medium if you don't know.
* Low (XPortal is still working fine, but sometimes a thing goes wrong). You can just log out and end the loop but the game is unplayable while the error is looping

**Additional information**
[LogOutput_ErrorLoop_7.log](https://github.com/SpikeHimself/XPortal/files/14178524/LogOutput_ErrorLoop_7.log)

Great mod, only request would be to add a private flag to portals so that only the creator could see it in the list, edit the name and link. i apreciate all the work you put into it.

**Comment by SpikeHimself** [comment]
Hi @Jester2020 thank you for reporting this issue.

Regarding:

> I have not tested it without any other mods installled. Currently running a farely large list that could be causing conflicts

Please do first test if the issue is really in XPortal. I have very limited time to research at the moment and I don't have all of the mods you listed to replicate your exact environment.
