### ISSUE TITLE
Broke in latest game version (10th April 2024)

### ISSUE THREAD

**Issue by mykkenny** [SpikeHimself/XPortal#97]
**Describe the bug**
Does not work in latest Valheim update (10th April)

**To Reproduce**

**Expected behaviour**

**LogOutput file(s)**

**Version**
Latest

**Environment**
Singleplayer

**Other mods**
Do you experience the issue also when you do not have any other mods installed? 
Yes

**Priority**
High (XPortal does not work at all anymore)

**Additional information**

**Comment by hvcrios** [comment]
Yep, can confirm

 - trying to launch the game with nothing but Jotunn and xportal it won't launch at all

- remove xportal from plugins folder and the game launches normally

**Comment by SpikeHimself** [comment]
I've just double checked and I am not finding any issues. Closing this for now since it seems to have been solved by a Jotunn update already.

If anything still goes wrong, let me know!
