### ISSUE TITLE
Xportal GUI not available 

### ISSUE THREAD

**Issue by huntzilla360c** [SpikeHimself/XPortal#98]
![Screenshot (1)](https://github.com/SpikeHimself/XPortal/assets/61102631/cc9fd785-74c4-4c0d-ad6e-668736bd970e)

![20240426173625_1](https://github.com/SpikeHimself/XPortal/assets/61102631/571f9de3-ee2e-4695-92bb-6e7eba838953)

![20240426173632_1](https://github.com/SpikeHimself/XPortal/assets/61102631/7151a914-fa7f-431f-8200-643c456ce1fd)

I'm having this issue, I've updated every single mod I could, there are no conflicts with any other mod but I'm seeing GUI issues with Jotun in the console. Jotun is installed but i dont think correctly, as i had all the jotun files just sitting in my plugins folder on my old PC where Xportal WAS working, but i looked on the ThunderStore and it says to just drop the Xportal and the Jotun folders into the Plugins folder

![Screenshot 2024-04-26 174725](https://github.com/SpikeHimself/XPortal/assets/61102631/bfbf0282-3625-46e3-86f4-9bc7ef55c28c)

For reference, I DID have both folders emptied into the plugins folder before these screenshots, but it wasn't working then either

**Describe the bug**
when I attempt to use the portal, I am met with the Vanilla portal UI and cannot select other portals as a destination.

**To Reproduce**
both on my, my brothers, and my friends' clients.

**LogOutput file(s)**
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/15135635/LogOutput.log)

**Version**
     v1.2.20

**Environment**
 Multiplayer Host
 Multiplayer Client    (ALL)
 Singleplayer

**Other mods**
I've isolated to only Bepin(5.4.22.0), Jotun (2.19.3), and Xportal (1.2.20) and it still wouldn't work.
You'll see the other mods I normally play with in the pictures.

**Priority**
* High (XPortal does not work at all anymore)

**Comment by huntzilla360c** [comment]
https://github.com/Valheim-Modding/Jotunn/issues/428

**Comment by SpikeHimself** [comment]
Hi @huntzilla360c - the good news: your logfile confirms Jotunn is running just fine! 

The bad news (for you), I am unable to reproduce your problem. It seems to be a conflict with another mod. Try disabling your mods and run only Jotunn and XPortal, and then enable your other mods one by one to find out which one is causing the issue.

If you find out which one is triggering the problem, maybe I can conjure up a compatibility work-around - but no promises!

**Comment by huntzilla360c** [comment]
![Screenshot 2024-04-29 161711](https://github.com/SpikeHimself/XPortal/assets/61102631/6098fd4a-583f-4424-963f-ff195cf54e53)


[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/15154538/LogOutput.log)

**Comment by SpikeHimself** [comment]
I noticed in your logfile it says your game is dated 25th of April. Mine is from the 13th. Are you running the public test (beta) version of Valheim?

**Comment by huntzilla360c** [comment]
![Screenshot 2024-04-29 180751](https://github.com/SpikeHimself/XPortal/assets/61102631/3ef0e197-153f-43e9-9220-51b9f38d2d19)

i dont think i am? am i?

**Comment by huntzilla360c** [comment]
![Screenshot 2024-04-29 180751](https://github.com/SpikeHimself/XPortal/assets/61102631/bc7547f1-9d12-4770-8534-001b73606890)

i dont think im on experimental/BETA, also I did download my stuff/update Val after almost a year of playing so that's probably when I did that

**Comment by SpikeHimself** [comment]
Very curious! Can you enable Debug Logging in BepInEx and share another output log?

Here's how you can do that: https://github.com/SpikeHimself/resources/wiki/BepInEx:-Enable-debug-logging

**Comment by huntzilla360c** [comment]
hey! so [MSchmoecker](https://github.com/MSchmoecker) said that the Bepin that i had was not the Thunderstore version (This is where I got it: https://github.com/BepInEx/BepInEx/releases ) and its working now. I'm sorry for the wild goose chase to the both of you, and thank you for your help

**Comment by SpikeHimself** [comment]
Glad to hear you got it sorted!
